var movies = [
	{'name' : 'על כלבים וגנבים 2', 		'video': 'על כלבים וגנבים 2.avi'},
	{'name' : 'אוליבר וחבורתו', 		'video': 'אוליבר וחבורתו.avi'},
	{'name' : 'אמיצה', 					'video': 'אמיצה.avi'},
	{'name' : 'אנגרי בירדס', 			'video': 'אנגרי בירדס.mp4'},
	{'name' : 'אסטריקס באחוזת האלים', 	'video': 'אסטריקס באחוזת האלים.avi'},
	{'name' : 'אצבעונית', 				'video': 'אצבעונית.avi'},
	{'name' : 'ארתור - בסך הכל רוקנרול', 'video': 'ארתור - בסך הכל רוקנרול.mp4'},
	{'name' : 'ארתור - חבר הולך לאיבוד', 'video': 'ארתור - חבר הולך לאיבוד.mp4'},
	{'name' : 'באג לייף', 				'video': 'באג לייף.avi'},
	{'name' : 'בילבי', 					'video': 'בילבי.mp4'},
	{'name' : 'בת הים הקטנה 3', 		'video': 'בת הים הקטנה 3.avi'},
	{'name' : 'בת הים הקטנה', 			'video': 'בת הים הקטנה.avi'},
	{'name' : 'דמבו הפיל המעופף', 		'video': 'דמבו הפיל המעופף.avi'},
	{'name' : 'האסלה הקסומה', 			'video': 'האסלה הקסומה.avi'},
	{'name' : 'הדינוזאור הטוב', 		'video': 'הדינוזאור הטוב.avi'},
	{'name' : 'הטירה הנעה', 			'video': 'הטירה הנעה.avi'},
	{'name' : 'היפה והחיה - 2017', 		'video': 'היפה והחיה - 2017.mp4'},
	{'name' : 'היפה והחיה (כפול)', 		'video': 'היפה והחיה (כפול).mkv'},
	{'name' : 'היפה והחיה 2 - חג המולד', 'video': 'היפה והחיה 2 - חג המולד.avi'},
	{'name' : 'היפהפיה הנרדמת', 		'video': 'היפהפיה הנרדמת.avi'},
	{'name' : 'היפהפיה והיחפן', 		'video': 'היפהפיה והיחפן.avi'},
	{'name' : 'המומינים בריביירה', 		'video': 'המומינים בריביירה.avi'},
	{'name' : 'המסע המופלא', 			'video': 'המסע המופלא.avi'},
	{'name' : 'המסע של דספרו', 			'video': 'המסע של דספרו.avi'},
	{'name' : 'הסייח השחור', 			'video': 'הסייח השחור.mp4'},
	{'name' : 'העיג (ענק ידידותי גדול)', 	'video': 'העיג (ענק ידידותי גדול).mp4'},
	{'name' : 'הצילו אני דג', 			'video': 'הצילו אני דג.mp4'},
	{'name' : 'הקול בראש', 				'video': 'הקול בראש.mp4'},
	{'name' : 'הרוח בערבי הנחל', 		'video': 'הרוח בערבי הנחל.mp4'},
	{'name' : 'השכן הקסום שלי טוטורו', 	'video': 'השכן הקסום שלי טוטורו.avi'},
	{'name' : 'וול אי', 				'video': 'וול אי.avi'},
	{'name' : 'חתולים בצמרת', 			'video': 'חתולים בצמרת.avi'},
	{'name' : 'למעלה', 					'video': 'למעלה.avi'},
	{'name' : 'לשבור את הקרח', 			'video': 'לשבור את הקרח.avi'},
	{'name' : 'מאה שירים ראשונים', 		'video': 'מאה שירים ראשונים.mpg'},
	{'name' : 'מבצע ביצה', 				'video': 'מבצע ביצה.mp4'},
	{'name' : 'מואנה', 					'video': 'מואנה.mp4'},
	{'name' : 'מולאן', 					'video': 'מולאן.mp4'},
	{'name' : 'מוצאים את נמו', 			'video': 'מוצאים את נמו.avi'},
	{'name' : 'מלך האריות', 			'video': 'מלך האריות.mp4'},
	{'name' : 'מפלצות בע\'\'מ', 		'video': 'מפלצות בע\'\'מ.avi'},
	{'name' : 'מרי פופינס', 			'video': 'מרי פופינס.mp4'},
	{'name' : 'נילס הולגרסון - הסרט', 	'video': 'נילס הולגרסון - הסרט.mp4'},
	{'name' : 'נסיך מצרים', 			'video': 'נסיך מצרים.avi'},
	{'name' : 'סנופי וצ\'ארלי בראון', 			'video': 'סנופי וצ\'ארלי בראון.avi'},
	{'name' : 'ספר הג\'ונגל', 			'video': 'ספר הג\'ונגל.avi'},
	{'name' : 'עליסה בארץ הפלאות', 		'video': 'עליסה בארץ הפלאות.avi'},
	{'name' : 'ענק הברזל', 				'video': 'ענק הברזל.mp4'},
	{'name' : 'פדינגטון', 				'video': 'פדינגטון.mkv'},
	{'name' : 'פו הדב סיפורו של פיל נפיל', 	'video': 'פו הדב סיפורו של פיל נפיל.avi'},
	{'name' : 'פו הדב', 				'video': 'פו הדב.mkv'},
	{'name' : 'פוניו על הצוק ליד הים', 	'video': 'פוניו על הצוק ליד הים.avi'},
	{'name' : 'פוקהונטס', 				'video': 'פוקהונטס.avi'},
	{'name' : 'פינוקיו', 				'video': 'פינוקיו.avi'},
	{'name' : 'פלונטר', 				'video': 'פלונטר.avi'},
	{'name' : 'פנטסיה', 				'video': 'פנטסיה.avi'},
	{'name' : 'צ\'ארלי בממלכת השוקולד', 'video': 'צ\'ארלי בממלכת השוקולד.avi'},
	{'name' : 'צעצוע של סיפור', 		'video': 'צעצוע של סיפור.flv'},
	{'name' : 'צעצוע של סיפור 2', 		'video': 'צעצוע של סיפור 2.avi'},
	{'name' : 'צעצוע של סיפור 3', 		'video': 'צעצוע של סיפור 3.avi'},
	{'name' : 'קסם של בית', 			'video': 'קסם של בית.avi'},
	{'name' : 'שלגיה ושבעת הגמדים', 	'video': 'שלגיה ושבעת הגמדים.avi'},
	{'name' : 'מרד התרנגולים', 			'video': 'מרד התרנגולים - מדובב.mpg'},
	{'name' : 'שון כבשון', 				'video': 'וואלאס וגרומיט\\Shaun.the.Sheep.Movie.2015.BRRip.HebSubs.XviD.AC3-Uploadil.avi'},
	{'name' : 'וואלאס וגרומיט - טיול לא מהעולם הזה', 'video': 'וואלאס וגרומיט\\Wallace and Gromit - A Grand Day Out.mp4'},
	{'name' : 'וואלאס וגרומיט - המכנסיים הלא נכונים', 'video': 'וואלאס וגרומיט\\Wallace.and.Gromit.In.the.Wrong.Trousers.1993.576p.BDRip.x264-HANDJOB.mkv'},
	{'name' : 'וואלאס וגרומיט - הרפתקה מצמררת', 'video': 'וואלאס וגרומיט\\Wallace and Gromit - A Close Shave.mp4'},
	{'name' : 'וואלאס וגרומיט - הארנב הקטלני', 'video': 'וואלאס וגרומיט\\וואלאס וגרומיט ותעלומת הארנב הקטלני.avi'},
	{'name': 'שאלתיאל קוואק', 'type': 'series', 'episodes': [
		{'name': 'פרק 01 שאלתיאל נולד', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 01 שאלתיאל נולד.mp4'},
		{'name': 'פרק 02 יום הולדת לשאלתיאל', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 02 יום הולדת לשאלתיאל.mp4'},
		{'name': 'פרק 03 אבן האודם', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 03 אבן האודם.mp4'},
		{'name': 'פרק 04 אבא חפי', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 04 אבא חפי.mp4'},
		{'name': 'פרק 05 הסוד של דולף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 05 הסוד של דולף.mp4'},
		{'name': 'פרק 06 המירוץ', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 06 המירוץ.mp4'},
		{'name': 'פרק 07 צופי הים', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 07 צופי הים.mp4'},
		{'name': 'פרק 08 הרימו עוגן', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 08 הרימו עוגן.mp4'},
		{'name': 'פרק 09 הבקבוק המוזר', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 09 הבקבוק המוזר.mp4'},
		{'name': 'פרק 10 המרבד המעופף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 10 המרבד המעופף.mp4'},
		{'name': 'פרק 11 הקרקס', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 11 הקרקס.mp4'},
		{'name': 'פרק 12 משחק השחמט', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 12 משחק השחמט.mp4'},
		{'name': 'פרק 13 הכתר האבוד של המלכה', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 13 הכתר האבוד של המלכה.mp4'},
		{'name': 'פרק 14 ספינת הדיג החדשה', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 14 ספינת הדיג החדשה.mp4'},
		{'name': 'פרק 15 סערה בים', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 15 סערה בים.mp4'},
		{'name': 'פרק 16 החיפוש אחרי הלוויתנים', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 16 החיפוש אחרי הלוויתנים.mp4'},
		{'name': 'פרק 17 חברים מהחלל החיצון', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 17 חברים מהחלל החיצון.mp4'},
		{'name': 'פרק 18 כוכב הקוטב', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 18 כוכב הקוטב.mp4'},
		{'name': 'פרק 19 האוקינוס שייך לכולם', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 19 האוקינוס שייך לכולם.mp4'},
		{'name': 'פרק 20 שאלתי נודד במדבר', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 20 שאלתי נודד במדבר.mp4'},
		{'name': 'פרק 21 המלך זקוק לכסף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 21 המלך זקוק לכסף.mp4'},
		{'name': 'פרק 22 שאיפותיו של דולף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 22 שאיפותיו של דולף.mp4'},
		{'name': 'פרק 23 הבריחה מהכלא', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 23 הבריחה מהכלא.mp4'},
		{'name': 'פרק 24 הקיסר דולף הראשון', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 24 הקיסר דולף הראשון.mp4'},
		{'name': 'פרק 25 נפילתו של דולף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 25 נפילתו של דולף.mp4'},
		{'name': 'פרק 27 אהבה ממבט ראשון', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 27 אהבה ממבט ראשון.mp4'},
		{'name': 'פרק 28 מתנה מהמלך', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 28 מתנה מהמלך.mp4'},
		{'name': 'פרק 29 המסע לאפריקה', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 29 המסע לאפריקה.mp4'},
		{'name': 'פרק 30 אי הצבים', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 30 אי הצבים.mp4'},
		{'name': 'פרק 31 המסע אל קרקעית הים', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 31 המסע אל קרקעית הים.mp4'},
		{'name': 'פרק 32 כדורי הזכוכית', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 32 כדורי הזכוכית.mp4'},
		{'name': 'פרק 33 חלום המערב הפרוע', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 33 חלום המערב הפרוע.mp4'},
		{'name': 'פרק 34 התרופה העתיקה', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 34 התרופה העתיקה.mp4'},
		{'name': 'פרק 35 המבוך', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 35 המבוך.mp4'},
		{'name': 'פרק 36 הזמר המפורסם', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 36 הזמר המפורסם.mp4'},
		{'name': 'פרק 37 הזמנה מן הנסיך', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 37 הזמנה מן הנסיך.mp4'},
		{'name': 'פרק 38 כוחה של אהבה', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 38 כוחה של אהבה.mp4'},
		{'name': 'פרק 39 המכשפה המאוהבת', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 39 המכשפה המאוהבת.mp4'},
		{'name': 'פרק 40 התוכנית הגנובה', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 40 התוכנית הגנובה.mp4'},
		{'name': 'פרק 41 התפרצות הר הגעש', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 41 התפרצות הר הגעש.mp4'},
		{'name': 'פרק 42 הצילו את הדרקון', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 42 הצילו את הדרקון.mp4'},
		{'name': 'פרק 43 המלך המהפכן', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 43 המלך המהפכן.mp4'},
		{'name': 'פרק 44 המזימות של דולף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 44 המזימות של דולף.mp4'},
		{'name': 'פרק 45 המחלה המסתורית', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 45 המחלה המסתורית.mp4'},
		{'name': 'פרק 46 הפגישה עם הליצן', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 46 הפגישה עם הליצן.mp4'},
		{'name': 'פרק 47 כינור הקסם', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 47 כינור הקסם.mp4'},
		{'name': 'פרק 48 תחרות הגולף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 48 תחרות הגולף.mp4'},
		{'name': 'פרק 49 המסע אל הקשת בענן', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 49 המסע אל הקשת בענן.mp4'},
		{'name': 'פרק 50 היכן קדירת הזהב', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 50 היכן קדירת הזהב.mp4'},
		{'name': 'פרק 51 הצילו את היערות', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 51 הצילו את היערות.mp4'},
		{'name': 'פרק 52 הניסיון האחרון של דולף', 'video': 'שאלתיאל קוואק\\שאלתיאל קוואק - פרק 52 הניסיון האחרון של דולף.mp4'},
	]},
	{'name': 'בילבי', 'type': 'series', 'image': 'בילבי-מצוייר', 'episodes': [
		{'name': 'פרק 1', 'type': 'youtube', 'id': 'CBWXP_5gxSw'},
		{'name': 'פרק 2', 'type': 'youtube', 'id': 'kgLCdl2q8XQ'},
		{'name': 'פרק 3', 'type': 'youtube', 'id': '5tc2MzqqHH8'},
		{'name': 'פרק 4', 'type': 'youtube', 'id': 'L878q4J48L8'},
		{'name': 'פרק 5', 'type': 'youtube', 'id': 's7lGfamDu3k'},
		{'name': 'פרק 6', 'type': 'youtube', 'id': '3aLRG6cK4zc'},
		{'name': 'פרק 7', 'type': 'youtube', 'id': 'hwyW1X6GsBw'},
		{'name': 'פרק 8', 'type': 'youtube', 'id': 'BhTNm0tCXD4'},
		{'name': 'פרק 9', 'type': 'youtube', 'id': 'TXH4h_S2cGk'},
		{'name': 'פרק 10', 'type': 'youtube', 'id': '-xgCHr10Z88'},
		{'name': 'פרק 11', 'type': 'youtube', 'id': '1C3a3EvTxsU'},
		{'name': 'פרק 12', 'type': 'youtube', 'id': 'BE4TvUUKpDc'},
		{'name': 'פרק 13', 'type': 'youtube', 'id': 'FMkSmiQ9U-0'},
		{'name': 'פרק 14', 'type': 'youtube', 'id': 'CZyBQOA47Rs'},
		{'name': 'פרק 15', 'type': 'youtube', 'id': '2n11hBdwJxQ'},
		{'name': 'פרק 16', 'type': 'youtube', 'id': 'OP_97s20uXU'},
		{'name': 'פרק 17', 'type': 'youtube', 'id': 's4MiEX3G3Zk'},
		{'name': 'פרק 18', 'type': 'youtube', 'id': 'XmNtmH3lGFc'},
		{'name': 'פרק 19', 'type': 'youtube', 'id': 'iZ61W9eNah0'},
		{'name': 'פרק 20', 'type': 'youtube', 'id': 'R-EmdfrfUUM'},
		{'name': 'פרק 21', 'type': 'youtube', 'id': 'kkIaFSYm4ts'},
		{'name': 'פרק 22', 'type': 'youtube', 'id': 'CohJOyzXETQ'},
		{'name': 'פרק 23', 'type': 'youtube', 'id': '5D-s3SUb558'},
		{'name': 'פרק 24', 'type': 'youtube', 'id': 'h9DwCQm6_hY'},
		{'name': 'פרק 25', 'type': 'youtube', 'id': 'zny85yBWrNY'},
		{'name': 'פרק 26', 'type': 'youtube', 'id': 'A_ckRx2itoo'},
	]},
	{'name': 'בארץ הקטקטים', 'type': 'series', 'episodes': [
		{'name': 'פרק 1 בחירת ילדי השנה', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 1 בחירת ילדי השנה.mp4'},
		{'name': 'פרק 2 מוקי רוצה להיות רופא', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 2 מוקי רוצה להיות רופא.mp4'},
		{'name': 'פרק 3 טחנת קמח', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 3 טחנת קמח.mp4'},
		{'name': 'פרק 4 זבובי האש', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 4 זבובי האש.mp4'},
		{'name': 'פרק 5 בחירות בארץ הקטקטים', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 5 בחירות בארץ הקטקטים.mp4'},
		{'name': 'פרק 7 תותי חורף', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 7 תותי חורף.mp4'},
		{'name': 'פרק 8 המלכה שילגית', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 8 המלכה שילגית.mp4'},
		{'name': 'פרק 9 הדביבון הפצוע', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 9 הדביבון הפצוע.mp4'},
		{'name': 'פרק 10 תחרות אריגת בדים', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 10 תחרות אריגת בדים.mp4'},
		{'name': 'פרק 12 הטלסקופ', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 12 הטלסקופ.mp4'},
		{'name': 'פרק 13 תחרות הדבש המתוק', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 13 תחרות הדבש המתוק.mp4'},
		{'name': 'פרק 14 הלידה', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 14 הלידה.mp4'},
		{'name': 'פרק 15 רכיבה על צפרדעים', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 15 רכיבה על צפרדעים.mp4'},
		{'name': 'פרק 16 הסנאית הפצועה', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 16 הסנאית הפצועה.mp4'},
		{'name': 'פרק 17 סוד האור האדום', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 17 סוד האור האדום.mp4'},
		{'name': 'פרק 18 הסייח הקטן', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 18 הסייח הקטן.mp4'},
		{'name': 'פרק 19 הביצה הענקית', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 19 הביצה הענקית.mp4'},
		{'name': 'פרק 20 אל הים הכחול', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 20 אל הים הכחול.mp4'},
		{'name': 'פרק 21 הביקור הראשון בים', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 21 הביקור הראשון בים.mp4'},
		{'name': 'פרק 22 הטיול על הקשת בענן', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 22 הטיול על הקשת בענן.mp4'},
		{'name': 'פרק 23 מונגה נעלם', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 23 מונגה נעלם.mp4'},
		{'name': 'פרק 24 גן הפרחים', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 24 גן הפרחים.mp4'},
		{'name': 'פרק 25 אבא ואמא של טיפטיפ', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 25 אבא ואמא של טיפטיפ.mp4'},
		{'name': 'פרק 26 חיים חדשים בכפר הקטקטים', 'type': 'movie', 'video': 'הקטקטים\\בארץ הקטקטים פרק 26 חיים חדשים בכפר הקטקטים.mp4'},
	]},
	{"name":"בלי סודות", "type":"series", "shuffle":true, "episodes":[
		{"name":"ביניים 3","type":"movie","video":"בלי סודות\\בלי סודות - ביניים 3.mp4"},
		{"name":"אותיות ס' ו- ע'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות ס' ו- ע'.mp4"},
		{"name":"חיריק ביניים","type":"movie","video":"בלי סודות\\בלי סודות - חיריק ביניים.mp4"},
		{"name":"חיריק 2","type":"movie","video":"בלי סודות\\בלי סודות - חיריק 2.mp4"},
		{"name":"שווא 1","type":"movie","video":"בלי סודות\\בלי סודות - שווא 1.mp4"},
		{"name":"אותיות י', פ'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות י', פ'.mp4"},
		{"name":"אותיות צ' ו-כ'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות צ' ו-כ'.mp4"},
		{"name":"שיר האותיות","type":"movie","video":"בלי סודות\\בלי סודות - שיר האותיות.mp4"},
		{"name":"ביניים צירה","type":"movie","video":"בלי סודות\\בלי סודות - ביניים צירה.mp4"},
		{"name":"צירה 3","type":"movie","video":"בלי סודות\\בלי סודות - צירה 3.mp4"},
		{"name":"שורוק 2","type":"movie","video":"בלי סודות\\בלי סודות - שורוק 2.mp4"},
		{"name":"אותיות נ' ו-ק'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות נ' ו-ק'.mp4"},
		{"name":"ביניים שווא","type":"movie","video":"בלי סודות\\בלי סודות - ביניים שווא.mp4"},
		{"name":"אותיות א' ו-ח","type":"movie","video":"בלי סודות\\בלי סודות - אותיות א' ו-ח.mp4"},
		{"name":"ביניים חולם","type":"movie","video":"בלי סודות\\בלי סודות - ביניים חולם.mp4"},
		{"name":"ביניים 5","type":"movie","video":"בלי סודות\\בלי סודות - ביניים 5.mp4"},
		{"name":"חולם 2","type":"movie","video":"בלי סודות\\בלי סודות - חולם 2.mp4"},
		{"name":"אותיות פ' - ו'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות פ' - ו'.mp4"},
		{"name":"ביניים 2","type":"movie","video":"בלי סודות\\בלי סודות - ביניים 2.mp4"},
		{"name":"צירה 4","type":"movie","video":"בלי סודות\\בלי סודות - צירה 4.mp4"},
		{"name":"שורוק 1","type":"movie","video":"בלי סודות\\בלי סודות - שורוק 1.mp4"},
		{"name":"האות ר'","type":"movie","video":"בלי סודות\\בלי סודות - האות ר'.mp4"},
		{"name":"אותיות ב' ו-ה'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות ב' ו-ה'.mp4"},
		{"name":"אותיות ב' ו- ד'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות ב' ו- ד'.mp4"},
		{"name":"חולם 1","type":"movie","video":"בלי סודות\\בלי סודות - חולם 1.mp4"},
		{"name":"חיריק 3","type":"movie","video":"בלי סודות\\בלי סודות - חיריק 3.mp4"},
		{"name":"חולם 3","type":"movie","video":"בלי סודות\\בלי סודות - חולם 3.mp4"},
		{"name":"חולם 4","type":"movie","video":"בלי סודות\\בלי סודות - חולם 4.mp4"},
		{"name":"חיריק 1","type":"movie","video":"בלי סודות\\בלי סודות - חיריק 1.mp4"},
		{"name":"ביניים 1","type":"movie","video":"בלי סודות\\בלי סודות - ביניים 1.mp4"},
		{"name":"בלי סודות סיפור קצר","type":"movie","video":"בלי סודות\\בלי סודות סיפור קצר.mp4"},
		{"name":"אותיות מ' ו- ז'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות מ' ו- ז'.mp4"},
		{"name":"אותיות ג' ו- ש'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות ג' ו- ש'.mp4"},
		{"name":"שווא 2","type":"movie","video":"בלי סודות\\בלי סודות - שווא 2.mp4"},
		{"name":"שורוק 3","type":"movie","video":"בלי סודות\\בלי סודות - שורוק 3.mp4"},
		{"name":"האות ת'","type":"movie","video":"בלי סודות\\בלי סודות - האות ת'.mp4"},
		{"name":"האות ל'","type":"movie","video":"בלי סודות\\בלי סודות - האות ל'.mp4"},
		{"name":"חיריק 4","type":"movie","video":"בלי סודות\\בלי סודות - חיריק 4.mp4"},
		{"name":"צירה 1","type":"movie","video":"בלי סודות\\בלי סודות - צירה 1.mp4"},
		{"name":"צירה 2","type":"movie","video":"בלי סודות\\בלי סודות - צירה 2.mp4"},
		{"name":"אותיות ט' ו-כ'","type":"movie","video":"בלי סודות\\בלי סודות - אותיות ט' ו-כ'.mp4"},
		{"name":"ביניים שורוק","type":"movie","video":"בלי סודות\\בלי סודות - ביניים שורוק.mp4"},
		{"name":"ביניים 4","type":"movie","video":"בלי סודות\\בלי סודות - ביניים 4.mp4"},
		{"name":"שווא 3","type":"movie","video":"בלי סודות\\בלי סודות - שווא 3.mp4"},
		{"name":"שורוק 4","type":"movie","video":"בלי סודות\\בלי סודות - שורוק 4.mp4"},
		{"name":"שווא 4","type":"movie","video":"בלי סודות\\בלי סודות - שווא 4.mp4"},
		{"name":"האות ש'","type":"movie","video":"בלי סודות\\בלי סודות - האות ש'.mp4"}
	]},
	{"name":"היה היה", "type":"series", "episodes":[
		{'name': 'פרק 1 - בריאת העולם', 'type': 'youtube', 'id': 'QuJionhH4so'},
		{'name': 'פרק 2 - האדם הניאנדרטלי', 'type': 'youtube', 'id': 'y34c8cNjCys'},
		{'name': 'פרק 3 - הקרו-מניון', 'type': 'youtube', 'id': '9CQDXhviDgE'},
		{'name': 'פרק 4 - הסהר הפורה', 'type': 'youtube', 'id': 'SasVGcBupDU'},
		{'name': 'פרק 5 - הקיסרות הראשונה', 'type': 'youtube', 'id': 'QUq_R5uEFtY'},
		{'name': 'פרק 6 - תקופתו של פריקלס', 'type': 'youtube', 'id': 'IbI93BjIi_E'},
		{'name': 'פרק 7 - שלום נוסח רומי', 'type': 'youtube', 'id': 'yybYd8d_CJc'},
		{'name': 'פרק 8 - עליית האיסלם', 'type': 'youtube', 'id': 'NJ0uokuke8s'},
		{'name': 'פרק 9 - בית קרל', 'type': 'youtube', 'id': '6ATVaApHrrE'},
		{'name': 'היה היה - פרק 10 - תור הוויקינגים', 'type': 'youtube', 'id': 'j53c8kOZHE4'},
		{'name': 'היה היה - פרק 11 - בוני הקתדרלות', 'type': 'youtube', 'id': '6weAkWiRGb4'},
		{'name': 'פרק 12 - מסעות מרקו פולו', 'type': 'youtube', 'id': 'Iol3fk4h8rk'},
		{'name': 'פרק 13 - מלחמת מאה השנים', 'type': 'youtube', 'id': 'AAiVKBUZ52E'},
		{'name': 'פרק 14 - המאה ה-15', 'type': 'youtube', 'id': 'KQHldV6H47M'},
		{'name': 'פרק 15 - תור הזהב של ספרד', 'type': 'youtube', 'id': 'UnEIw3plWJc'},
		{'name': 'היה היה - פרק 16 - אנגליה בימי אליזבת', 'type': 'youtube', 'id': 'EKu5HHBD-ag'},
		{'name': 'היה היה - פרק 17 - תור הזהב במחוזות המאוחדים', 'type': 'youtube', 'id': 'TnU8_q5fkZU'},
		{'name': 'פרק 18 - תקופתו של לואי ה-14', 'type': 'youtube', 'id': '-oVJIGpRkbs'},
		{'name': 'פרק 19 - תקופתו של פטר הגדול', 'type': 'youtube', 'id': '7aKxMLU5Zis'},
		{'name': 'פרק 20 - המאה של המאורות הגדולים', 'type': 'youtube', 'id': 'BCyOXO5iltI'},
		{'name': 'פרק 21 - אמריקה', 'type': 'youtube', 'id': 'AdnmO7pQCkI'},
		{'name': 'פרק 22 - המהפכה הצרפתית', 'type': 'youtube', 'id': '1ktbZlElJLc'},
		{'name': 'פרק 23 - אביב העמים', 'type': 'youtube', 'id': 'hI9b1ndTYRI'},
		{'name': 'פרק 24 - התקופה היפה בצרפת', 'type': 'youtube', 'id': 'bAf0wS2WHXY'},
		{'name': 'פרק 25 - השנים העליזות', 'type': 'youtube', 'id': 'MDEZIHKEpA8'},
		{'name': 'פרק 26 - היה יהיה', 'type': 'youtube', 'id': 'xl7Pf0skqxM'},
	]},
	{"name":"רחוב סומסום", "type":"series", "shuffle":true, "episodes":[
		{'name': 'קיפי בבית ספר', 'type': 'youtube', 'id': 'S9yMeuZnqf8'},
		{'name': 'קיפי עוזר לאמא', 'type': 'youtube', 'id': 'WpxDIpSDA_o'},
		{'name': 'מים', 'type': 'youtube', 'id': 'UNO4gqWAeQE'},
		{'name': 'קיפי מצייר את מוישה', 'type': 'youtube', 'id': '8Ce3d4Y1lXc'},
		{'name': 'קיפי פוגש את נתן', 'type': 'youtube', 'id': 'irGBfOr5M-0'},
		{'name': 'כדורסל', 'type': 'youtube', 'id': 'b9cppzqQEdk'},
		{'name': 'מעשה חלם', 'type': 'youtube', 'id': '8xdyV-zhfoM'},
		{'name': 'חנוכה', 'type': 'youtube', 'id': '5uRyIMy2ktA'},
		{'name': 'קיפי מוצא חמור', 'type': 'youtube', 'id': 'UbebFD2BzSQ'},
		{'name': 'משחק פורים', 'type': 'youtube', 'id': '5dHad5l61t0'},
		{'name': 'שערא סימסים - דומים ושונים', 'type': 'youtube', 'id': 'TIPNuXPEcUY'},
		{'name': 'החנות של אופניק', 'type': 'youtube', 'id': 'BAowN8NTKcU'},
		{'name': 'לוח השנה', 'type': 'youtube', 'id': 'G3MiJAeHGg0'},
		{'name': 'הופ - גיבור', 'type': 'youtube', 'id': 'eC1MALM5FiQ'},
		{'name': 'הופ - להקשיב', 'type': 'youtube', 'id': 'N2j2UvTTMhY'},
		{'name': 'הופ - המופע של אלמו: הגואקמולי', 'type': 'youtube', 'id': 'g8Lr5MtzHug'},
		{'name': 'הופ - מה זה השתקפות?', 'type': 'youtube', 'id': '2-J8pvV-pac'},
		{'name': 'הופ - סרטי עוגיפלצת: מלחמת המאפים', 'type': 'youtube', 'id': 'ROYur1kaCBc'},
		{'name': 'חנוכה', 'type': 'youtube', 'id': '5uRyIMy2ktA'},
		{'name': 'המכונית של אופניק', 'type': 'youtube', 'id': '0SS0CZnLAmY'},
		{'name': 'שארע סימסים - הקוסם מארץ אוף', 'type': 'youtube', 'id': 'LMo1nKSsWY0'},
		{'name': 'סביבונים', 'type': 'youtube', 'id': 'KG3fqtrIZnc'},
		{'name': 'קיפי יהודה המכבי', 'type': 'youtube', 'id': 'gAJqal9ng0c'},
		{'name': 'רוצה להיות שם', 'type': 'youtube', 'id': 'LSXLpgdRtyU'},
		{'name': 'פרק 3', 'type': 'youtube', 'id': 'MU_6sFI8iOY'},
		{'name': 'פרק 2', 'type': 'youtube', 'id': 'e4r1CYjafDU'},
		{'name': 'ציפורת', 'type': 'youtube', 'id': '1-rQVTe-L6c'},
		{'name': 'לקט אריק ובנץ', 'type': 'youtube', 'id': 'KHyURd39OeI'},
		{'name': 'הופ - השעשועון של אביגיל', 'type': 'youtube', 'id': '7YxR-zK2udk'},
		{'name': 'חבר של קבע', 'type': 'youtube', 'id': '6Fgjb-n-LbY'},
		{'name': 'ט"ו בשבט', 'type': 'youtube', 'id': 'f4Z0MxSQ3dc'},
		{'name': 'שבועות', 'type': 'youtube', 'id': '7MsiQVLXANI'},
		{'name': 'קיפי פוגש את גבי', 'type': 'youtube', 'id': 'xQix4Pe0iZA'},
		{'name': 'שערא סימסים - סוכות', 'type': 'youtube', 'id': 'W0JxRyqkbBI'},
		{'name': 'המכונית של מוישה אופניק', 'type': 'youtube', 'id': 'Y8CFfUbvuZI'},
		{'name': 'פרק 2', 'type': 'youtube', 'id': 'e4r1CYjafDU'},
		{'name': 'פסח', 'type': 'youtube', 'id': 'hBsDetJvy2E'},
		{'name': 'פרק כלשהו', 'type': 'youtube', 'id': 'iUMpOpi865E'},
		{'name': 'שארע סימסים - אגדות', 'type': 'youtube', 'id': 'URnWguaOp0k'},
		{'name': 'הופ - המופע של אלמו: פיצה', 'type': 'youtube', 'id': 'xRXRC7gbyno'},
		{'name': 'הופ - בית ספר לפיות: משימת סינדרלה', 'type': 'youtube', 'id': 'HX79ahX4aFg'},
		{'name': 'שארע סימסים - פרק כלשהו', 'type': 'youtube', 'id': '6j4qBatnpgE'},
		{'name': 'שארע סימסים - חנוכה', 'type': 'youtube', 'id': 'C7mlEaKbmJA'},
		{'name': 'הופ - הטרקטור של אלמו', 'type': 'youtube', 'id': 'yojxEBKFtJQ'},
		{'name': 'הופ - חודשי השנה: חשוון', 'type': 'youtube', 'id': 'dwaYg2KN0LU'},
		{'name': 'לקט החבובות', 'type': 'youtube', 'id': 'GcoeFuw3Y6c'},
		{'name': 'פורים', 'type': 'youtube', 'id': 'LeUYIoUZz1o'},
		{'name': 'שארע סימסים - כדורגל', 'type': 'youtube', 'id': '4n4G8W7MTbw'},
		{'name': 'נתן במילואים', 'type': 'youtube', 'id': 'JspOW8A1qRI'},
		{'name': 'הופ - בית ספר לפיות: הגידו גזונדנשניפל', 'type': 'youtube', 'id': 'XjDUpDNP4C4'},
		{'name': 'הופ - לחמם את האף', 'type': 'youtube', 'id': 'zLgFM0fqFEI'},
		{'name': 'יונה חולה - חלק א', 'type': 'youtube', 'id': 'pyujS-J6QtQ'},
		{'name': 'יונה חולה - חלק ב', 'type': 'youtube', 'id': 'ctNlFiL3p2I'},
		{'name': 'יונה חולה - חלק ג', 'type': 'youtube', 'id': '5wqHGTs5IkU'},
		{'name': 'הופ - המופע של אלמו: הסיפור על רב החובל', 'type': 'youtube', 'id': 'RY7b7z6g3AQ'},
		{'name': 'שארע סימסים - פרק כלשהו (2)', 'type': 'youtube', 'id': '1DwisSsu27I'},
		{'name': 'קיפי איבד את הקול - חלק א', 'type': 'youtube', 'id': 'yE_2gHTrwrY'},
		{'name': 'קיפי איבד את הקול - חלק ב', 'type': 'youtube', 'id': 't-QESXdXaXc'},
		{'name': 'קיפי איבד את הקול - חלק ג', 'type': 'youtube', 'id': 'ZqkoYt9y2jw'},
		{'name': 'הופ - סופר כרובי: בעיה קוצנית', 'type': 'youtube', 'id': 'SenPekKBrKE'},
		{'name': 'הופ - בית ספר לבריאות: לזוז זה בזבוז', 'type': 'youtube', 'id': 'EB1uREA2mUc'},
		{'name': 'הופ - סופר כרובי: גלגלות', 'type': 'youtube', 'id': 'zwyRGU6lxkQ'},
		{'name': 'הופ - בית הספר לבריאות: בננה רקובה', 'type': 'youtube', 'id': '8KuP7Lyo8FE'},
	]},
	{"name":"פרפר נחמד", "type":"series", "shuffle":true, "episodes":[
		{'name': 'מה שייך למה', 'type': 'youtube', 'id': 'OsagfJKEGHw'},
		{'name': 'משחקים וצעצועים', 'type': 'youtube', 'id': 'Rp4_wxECd0M'},
		{'name': 'אחים', 'type': 'youtube', 'id': 'LK8Tckf9FuE'},
		{'name': 'הגשם הראשון', 'type': 'youtube', 'id': 'ecEyl8-y2R8'},
		{'name': 'נולי חולה', 'type': 'youtube', 'id': 'R5KSK5DiNic'},
		{'name': 'רגליים', 'type': 'youtube', 'id': 'n-_JouCF9E0'},
		{'name': 'יום ראשון בגן', 'type': 'youtube', 'id': 'uQXCUDkS3kc'},
		{'name': 'חורף', 'type': 'youtube', 'id': 'TRBaRquwoLE'},
		{'name': 'טיול בארץ', 'type': 'youtube', 'id': 'HYxfdyzbn7o'},
		{'name': 'בחירה', 'type': 'youtube', 'id': 'm_ZC4YmPbJg'},
		{'name': 'פורים', 'type': 'youtube', 'id': 'YOVIiWUPJLc'},
		{'name': 'מגוון', 'type': 'youtube', 'id': 'L9T9zQAVdEM'},
		{'name': 'קצר ארוך', 'type': 'youtube', 'id': 'b1QN0vEo5oE'},
		{'name': 'בית', 'type': 'youtube', 'id': 'Hb-UCviMddE'},
		{'name': 'זהירות', 'type': 'youtube', 'id': 'O1bUqjjIna0'},
		{'name': 'בעלי חיים (דגיגי)', 'type': 'youtube', 'id': 'yqAXBs80aSM'},
		{'name': 'פעמונים', 'type': 'youtube', 'id': 'XTsNphlAnHw'},
		{'name': 'דמי החנוכה של פינגי', 'type': 'youtube', 'id': 'xd75vQjNUlc'},
		{'name': 'חנוכה חג מדליק', 'type': 'youtube', 'id': 'ZQzBeyTaxUI'},
		{'name': 'כשחולים', 'type': 'youtube', 'id': 'bUUTBfNr234'},
		{'name': 'אני חולה', 'type': 'youtube', 'id': 'KN-rO0Iz1MU'},
		{'name': 'הידד פורים', 'type': 'youtube', 'id': 'UOvQXSdGg2o'},
		{'name': 'מזג אוויר בהזמנה', 'type': 'youtube', 'id': 'EWxDFupfk6M'},
		{'name': 'צורות', 'type': 'youtube', 'id': 'euUsKlpiqnk'},
		{'name': 'סימנים', 'type': 'youtube', 'id': 'UpE4mRKqKoY'},
		{'name': 'בץ הולך לגן', 'type': 'youtube', 'id': 'ErUpwiuMLlc'},
		{'name': 'אוכל', 'type': 'youtube', 'id': 'WN-WZ7jiQsI'},
		{'name': 'שינה', 'type': 'youtube', 'id': 'LZQi1bn_AtQ'},
		{'name': 'קופסאות', 'type': 'youtube', 'id': 'wn2OkiL-2N8'},
		{'name': 'דברי חכמים בנחת נשמעים', 'type': 'youtube', 'id': 'IFuTZ-jzlJM'},
		{'name': 'ויהי ערב', 'type': 'youtube', 'id': 'I6OIKnROcYU'},
		{'name': 'עץ ונייר', 'type': 'youtube', 'id': 'jdlPBFs8EEM'},
		{'name': 'מיהו פופו?', 'type': 'youtube', 'id': 'V8VrHFxX4wc'},
		{'name': 'שבועות', 'type': 'youtube', 'id': 'rEfxKnGPdxM'},
		{'name': 'עיגולים', 'type': 'youtube', 'id': 'pvxIodAk9Gw'},
		{'name': 'געגועים ופרידה', 'type': 'youtube', 'id': 'vr6hFW7JJ-c'},
		{'name': 'להיות לבד, להיות יחד', 'type': 'youtube', 'id': 'vFAyONh3JAg'},
		{'name': 'פסח חג המצות', 'type': 'youtube', 'id': '9C-2WMd2HTo'},
		{'name': 'איך בוחרים', 'type': 'youtube', 'id': '5eqH4FYWD_8'},
		{'name': 'המעיל החום של הדוד נחום', 'type': 'youtube', 'id': 'jX8QqtbMR0g'},
		{'name': 'ידיים', 'type': 'youtube', 'id': 'ffVNySbmzMs'},
		{'name': 'גם אני יכול', 'type': 'youtube', 'id': 'mEA5EOQQIiA'},
		{'name': 'אני זה אני', 'type': 'youtube', 'id': 'FSE7Lo1nNJQ'},
		{'name': 'אני וגופי', 'type': 'youtube', 'id': 'ES-Bdn4tz7o'},
		{'name': 'פחד במיטה', 'type': 'youtube', 'id': 'GHszzdntgJE'},
		{'name': 'שאלות', 'type': 'youtube', 'id': 'OdSuZJRgXi4'},
		{'name': 'לאן נעלמה המברשת?', 'type': 'youtube', 'id': 'bROh0DwOg3w'},
		{'name': 'קיץ', 'type': 'youtube', 'id': 'jUoFCF7eWxo'},
		{'name': 'כדאי לזכור', 'type': 'youtube', 'id': 'rrpqq0JBJck'},
		{'name': 'מוסיקה בכל מקום', 'type': 'youtube', 'id': 'tYkvlewVJNE'},
		{'name': 'ירקות', 'type': 'youtube', 'id': 'j5SRRKIlzyI'},
		{'name': 'חורף', 'type': 'youtube', 'id': '-GL1TxOkqRM'},
		{'name': 'ימי השבוע', 'type': 'youtube', 'id': 'ObH_oaWvan4'},
		{'name': 'פינגי מנומס', 'type': 'youtube', 'id': 'm6H7L219pbE'},
		{'name': 'זרעים', 'type': 'youtube', 'id': 'OsEnO-lApnE'},
		{'name': 'מתגעגעים לדודו', 'type': 'youtube', 'id': '0cmi5piQeB8'},
		{'name': 'דרך ארץ', 'type': 'youtube', 'id': 'DvXx_1Dllu4'},
		{'name': 'פינגי מחפש בית', 'type': 'youtube', 'id': 'd6M5z8bR3Dc'},
		{'name': 'המשפחה שלי', 'type': 'youtube', 'id': 'EPERt8XvNIg'},
		{'name': 'יום אחד עם סבא', 'type': 'youtube', 'id': 'PYjl55q0jSg'},
		{'name': 'בוא נצייר, זה נהדר', 'type': 'youtube', 'id': '1aJ23vFqV7M'},
		{'name': 'חנוכה', 'type': 'youtube', 'id': '-ocfNHYYcwE'},
		{'name': 'סוכות', 'type': 'youtube', 'id': 'LfWm6hlpD7k'},
		{'name': 'מיום ראשון עד שבת (יומן לטלפון)', 'type': 'youtube', 'id': 'wLnqtIxMA2U'},
		{'name': 'שומעים קולות, שומעים צלילים', 'type': 'youtube', 'id': 'N_9TzALNLRk'},
		{'name': 'יום הולדת', 'type': 'youtube', 'id': 'Z47gWAye9Uw'},
		{'name': 'קיץ', 'type': 'youtube', 'id': 'CUiO7Qtn_Ts'},
		{'name': 'בית לגור בו', 'type': 'youtube', 'id': 'm2e3PbgZKQ8'},
		{'name': 'פסים פסים', 'type': 'youtube', 'id': 'pSxHhB5iMmY'},
		{'name': 'בגדים לתיאטרון', 'type': 'youtube', 'id': 'Ktjf4_f1eLc'},
		{'name': 'כבר נורא מאוחר', 'type': 'youtube', 'id': 'MeRR0lelVXY'},
		{'name': 'צמיחה', 'type': 'youtube', 'id': 'VgWn8q_2CEU'},
		{'name': 'מפלצות', 'type': 'youtube', 'id': 'bY5QbCoYq-4'},
		{'name': 'שנה טובה', 'type': 'youtube', 'id': 'N_3w-msRKYA'},
		{'name': 'ניקיון', 'type': 'youtube', 'id': 'zJhX1tzJFNc'},
		{'name': 'פרחים', 'type': 'youtube', 'id': 'oK0WanCNRx4'},
		{'name': 'חורים, חורים', 'type': 'youtube', 'id': 'fLQAaknls64'},
		{'name': 'עוברים דירה', 'type': 'youtube', 'id': 'eM6rO7iL0H4'},
		{'name': 'חגי תשרי - חלק 1', 'type': 'youtube', 'id': '9c0u2RDR3MA'},
		{'name': 'לקט שירים וסיפורים', 'type': 'youtube', 'id': 'Xi9MCIzmq70'},
		{'name': 'מראות', 'type': 'youtube', 'id': 'ToV9IdeJDgU'},
		{'name': 'חמשת החושים', 'type': 'youtube', 'id': 'Mgm6FXeRPXg'},
		{'name': 'קטן גדול', 'type': 'youtube', 'id': '43Kn825Qa5Q'},
		{'name': 'אם רוצים לדעת, שואלים', 'type': 'youtube', 'id': '81HST8n_HdI'},
		{'name': 'בלשים ותעלומות', 'type': 'youtube', 'id': 'oyk5ucBHh5Y'},
		{'name': 'יום הולדת לשבי', 'type': 'youtube', 'id': '6zUdtxqwfps'},
		{'name': 'יום כיף במטבח', 'type': 'youtube', 'id': 'Kfv72_PamUE'},
		{'name': 'כיף לנסוע', 'type': 'youtube', 'id': 'Qbz-BAYyGUM'},
		{'name': 'פנים', 'type': 'youtube', 'id': '9PFqfliTWik'},
		{'name': 'דבר אלי בפתקים', 'type': 'youtube', 'id': 'uy5jd_iJEiU'},
		{'name': 'אלפא-ביתא', 'type': 'youtube', 'id': '0Bv4XPlgpT0'},
		{'name': 'פסח בא', 'type': 'youtube', 'id': 'C61bi4AhfWU'},
		{'name': 'צבעים', 'type': 'youtube', 'id': 'qmpQGT7y00A'},
		{'name': 'לכבוד החנוכה', 'type': 'youtube', 'id': 'GeOaKzRsWJA'},
		{'name': 'מכתב לאפי', 'type': 'youtube', 'id': 'heA8ln6DCXA'},
		{'name': 'מיום ראשון עד שבת', 'type': 'youtube', 'id': 'm_S4M_BiuVM'},
		{'name': 'מושגי מרחב', 'type': 'youtube', 'id': 'A7LN3NHq_uA'},
		{'name': 'בא לשכונה חבר חדש', 'type': 'youtube', 'id': 'JyTayW1Xzmg'},
		{'name': 'כל אחד אוהב משהו אחר', 'type': 'youtube', 'id': 'RdeO1Nao1mo'},
		{'name': 'טוב לצחוק', 'type': 'youtube', 'id': 'd5QbnbbfoN4'},
		{'name': 'הזמנה לקונצרט', 'type': 'youtube', 'id': 'EvT0sswPXlg'},
		{'name': 'עקבות בחול', 'type': 'youtube', 'id': '4NSnKi0SrWk'},
		{'name': 'עץ-עץ', 'type': 'youtube', 'id': '8jXGlv3dZ4A'},
		{'name': 'מים מים', 'type': 'youtube', 'id': 'T80RvqdxJO4'},
		{'name': 'ראש השנה', 'type': 'youtube', 'id': 'f2hIwxGqvMY'},
		{'name': 'כשחולים', 'type': 'youtube', 'id': 'YBRDR45EOTA'},
		{'name': 'מה נשמע', 'type': 'youtube', 'id': 'eVnqn0nf_sA'},
		{'name': 'יום ולילה', 'type': 'youtube', 'id': 'pX6hzNg5hIA'},
		{'name': 'קולות וצלילים', 'type': 'youtube', 'id': 'QoIALdkI4mw'},
		{'name': 'זה הקיץ שאנו אוהבים', 'type': 'youtube', 'id': 'Klwc0HKrk14'},
		{'name': 'בתיאבון', 'type': 'youtube', 'id': 'E0Os6DgFnu4'},
		{'name': 'קסמי צבעים', 'type': 'youtube', 'id': 'I2V1a9gnUsw'},
		{'name': 'ספרים', 'type': 'youtube', 'id': 'fyxIIkhh8nw'},
		{'name': 'אכול ושתה', 'type': 'youtube', 'id': '88XlvFPVyVM'},
		{'name': 'הבה נתפייסה', 'type': 'youtube', 'id': '9ZnOl2u2Ba4'},
		{'name': 'הפכים', 'type': 'youtube', 'id': 'ZvdCqWx8TiI'},
		{'name': 'מקצועות', 'type': 'youtube', 'id': 'G14ia7hk0l8'},
		{'name': 'גבוה-נמוך', 'type': 'youtube', 'id': 'ytd-IZAFzoE'},
		{'name': 'חברים טובים', 'type': 'youtube', 'id': 'z_5dxWVZ5Q0'},
		{'name': 'מה אתם חושבים', 'type': 'youtube', 'id': 'SgVz688eeVw'},
		{'name': 'כמה טוב עם סבתא', 'type': 'youtube', 'id': 'nPHUyab2lzE'},
		{'name': 'איזה קצב', 'type': 'youtube', 'id': 'xbv_OThQL94'},
		{'name': 'שמות', 'type': 'youtube', 'id': 'dNcrAF8zX5I'},
		{'name': 'בדיוק ולא בערך', 'type': 'youtube', 'id': 'xwXMGN99t2w'},
		{'name': 'כולנו שונים', 'type': 'youtube', 'id': 'BjHqwams-64'},
		{'name': 'חגיגה של צבעים', 'type': 'youtube', 'id': 'x57HninZFMY'},
		{'name': 'כלב במתנה', 'type': 'youtube', 'id': 'xW0dN_KKLX0'},
		{'name': 'למעלה למטה', 'type': 'youtube', 'id': 'f3vChYoCy-o'},
		{'name': 'חגיגת פורים', 'type': 'youtube', 'id': 'twEW2PgbAjo'},
		{'name': 'שלם וחצי', 'type': 'youtube', 'id': 'MaOK5Aq0bfE'},
		{'name': 'כדאי לנסות עוד ועוד', 'type': 'youtube', 'id': '507NOp9-tiA'},
		{'name': 'מתנה צבעונית', 'type': 'youtube', 'id': 'LwSAxxUazZY'},
		{'name': 'אם אומרים אז מבינים', 'type': 'youtube', 'id': 'QWNplcKGgrU'},
		{'name': 'מי צודק', 'type': 'youtube', 'id': 'jx21vE2c9h0'},
		{'name': 'בעלי חיים (גדילה)', 'type': 'youtube', 'id': 'MYa_08Xz9vk'},
		{'name': 'שמח במטבח', 'type': 'youtube', 'id': 'PwzKk7xuSKM'},
		{'name': 'חדש ישן', 'type': 'youtube', 'id': 'nliVr1LWXr4'},
		{'name': 'קטמלוק', 'type': 'youtube', 'id': '9DFFJXR__7w'},
		{'name': 'שתי ידיים', 'type': 'youtube', 'id': 'os5sy6g3Chs'},
		{'name': 'שנה טובה', 'type': 'youtube', 'id': 'WQWeyAYLy7w'},
		{'name': 'אנדרלמוסיה', 'type': 'youtube', 'id': 'q3V-2xdsskE'},
		{'name': 'אדום, כחול, צהוב', 'type': 'youtube', 'id': 'LSBxgI4wIDk'},
		{'name': 'במשפחה (אח גדול אח קטן)', 'type': 'youtube', 'id': '5-a1gdO1UmM'},
		{'name': 'אכול ושתה', 'type': 'youtube', 'id': 'NkdXs44DH1c'},
		{'name': 'המון אפשרויות', 'type': 'youtube', 'id': 'k7fuMxxuDTY'},
		{'name': 'איזה חלום', 'type': 'youtube', 'id': 'wrMpEyBLAFg'},
		{'name': 'מה אפשר ומה אי אפשר', 'type': 'youtube', 'id': 'nHhSLci29mA'},
		{'name': 'אצלי הכל בסדר', 'type': 'youtube', 'id': 'hnYeUaV3gZo'},
		{'name': 'פיאנו-פורטה', 'type': 'youtube', 'id': '66_mUL7asIc'},
		{'name': 'למה אסור', 'type': 'youtube', 'id': 'r_xxlu1Uow4'},
		{'name': 'המודעה של פינגי', 'type': 'youtube', 'id': 'V2dJFcRYWgk'},
		{'name': 'נייר', 'type': 'youtube', 'id': 'an5B7cpz2WM'},
		{'name': 'סבתא להיות זה קל', 'type': 'youtube', 'id': 'illVZ2nGtts'},
		{'name': 'כף כפית מזלג סכין', 'type': 'youtube', 'id': 'nffRwaTQZ7Q'},
		{'name': 'מילים', 'type': 'youtube', 'id': 'flHB8ZvZGgs'},
		{'name': 'כשאהיה גדול', 'type': 'youtube', 'id': 'Up0fJqYrhyM'},
		{'name': 'חורף', 'type': 'youtube', 'id': 'cXUZ3_IXioc'},
		{'name': 'הוא והיא', 'type': 'youtube', 'id': '78vmuBBl4SI'},
		{'name': 'במשפחה שלנו', 'type': 'youtube', 'id': 'Now08GCtQv0'},
		{'name': 'פח אשפה יפה', 'type': 'youtube', 'id': 'uNWK3eRS1yg'},
		{'name': 'עזרה בבית', 'type': 'youtube', 'id': 'VF-U6LOEjBs'},
		{'name': 'שלי, שלך, שלנו', 'type': 'youtube', 'id': 'b6TzKpIKhFo'},
		{'name': 'לכל אחד יש שם', 'type': 'youtube', 'id': 'v3Tl1p3WCik'},
		{'name': 'תן חיוך', 'type': 'youtube', 'id': '_-PYoP2dPq0'},
		{'name': 'מה עיגול יכול?', 'type': 'youtube', 'id': 'xJ7gDeMpVOE'},
		{'name': 'תרופות של חורף', 'type': 'youtube', 'id': 'IFkd-lFH_4A'},
		{'name': 'במשפחה שלנו', 'type': 'youtube', 'id': 'J-pCL6f4nJw'},
		{'name': 'מברשות', 'type': 'youtube', 'id': '16c3fCqJ9wg'},
		{'name': 'ספרים הם חברים', 'type': 'youtube', 'id': 'fxRuKrGBmHs'},
		{'name': 'מכתב לסבא וסבתא', 'type': 'youtube', 'id': 'LsB_JzEF4j8'},
		{'name': 'לפעמים פוחדים', 'type': 'youtube', 'id': 'QRkiWZWX4M4'},
		{'name': 'ציונות', 'type': 'youtube', 'id': 'fTCNeGrQrwY'},
		{'name': 'טו בשבט', 'type': 'youtube', 'id': 'OzQBvC3EWzI'},
		{'name': 'אקו לוגי', 'type': 'youtube', 'id': 'JGSchxLSZcY'},
		{'name': 'ברוכים הבאים', 'type': 'youtube', 'id': 'CHfq9NBP1P4'},
		{'name': 'פרחים לחג העצמאות', 'type': 'youtube', 'id': 'KvX0-MarWOo'},
		{'name': 'מה לעשות - לעשות', 'type': 'youtube', 'id': 'REu0_FpOlLA'},
		{'name': 'כבר נורא מאוחר', 'type': 'youtube', 'id': 'cd1dU-qzpVk'},
		{'name': 'לחיות בשלום', 'type': 'youtube', 'id': 'SlxkJKB2pwQ'},
		{'name': 'בגד ללבוש', 'type': 'youtube', 'id': 'GJvLm8U35hw'},
		{'name': 'זה קורה בירושלים', 'type': 'youtube', 'id': 'XAcSCOqEzIU'},
		{'name': 'טובים השניים מן האחד', 'type': 'youtube', 'id': '3QiUKLGFK1s'},
		{'name': 'שקט בבקשה', 'type': 'youtube', 'id': 'Vq7tvH4zqys'},
		{'name': 'שלום ולהתראות', 'type': 'youtube', 'id': 'AKSkaGAAuVk'},
		{'name': 'להסתדר יחד', 'type': 'youtube', 'id': 'yynUoOYWcOQ'},
		{'name': 'אילו השמש היתה שלי', 'type': 'youtube', 'id': 'vhCxEkLh2QA'},
		{'name': 'גדול קטן', 'type': 'youtube', 'id': 'd-zCPdq4IP0'},
		{'name': 'חמישים שנה למדינה', 'type': 'youtube', 'id': 'xQXHu1Pr5OE'},
		{'name': 'אכפת לי', 'type': 'youtube', 'id': '5U3vG5iQR1Y'},
		{'name': 'כל אחד אוהב משהו אחר', 'type': 'youtube', 'id': 'Ns57apJgRuE'},
		{'name': 'משהו כאן לא בסדר', 'type': 'youtube', 'id': '2IX5L1LXYY8'},
		{'name': 'צלילים בכל מיני צבעים', 'type': 'youtube', 'id': '8VQRyr9MOJE'},
		{'name': 'כמה כמה', 'type': 'youtube', 'id': 'DxUM69eOR1o'},
		{'name': 'חמש חמש', 'type': 'youtube', 'id': '5CRjc-r_6fk'},
		{'name': 'נעליים לרגליים', 'type': 'youtube', 'id': '6Lk2od_spRc'},
		{'name': 'ברוך הבא פינגי', 'type': 'youtube', 'id': '7pTKJZSe5QY'},
		{'name': 'להיות מישהו אחר', 'type': 'youtube', 'id': 'P9jaOF-u5BE'},
		{'name': 'מה קודם מה אחר כך', 'type': 'youtube', 'id': '-ynDKF-LCOs'},
		{'name': 'משחקים מוסיקליים', 'type': 'youtube', 'id': 'mSfEp-otQ2M'},
		{'name': 'חלק ושלם', 'type': 'youtube', 'id': 'lpsfTRswwdo'},
		{'name': 'איך אפשר לזכור', 'type': 'youtube', 'id': 'wgBxDN-BmhE'},
		{'name': 'בית', 'type': 'youtube', 'id': 'pjMfOJGkL3U'},
		{'name': 'לקט ליום החינוך', 'type': 'youtube', 'id': 'bQtlEZ2pUHQ'},
		{'name': 'בעלי חיים (אימוץ)', 'type': 'youtube', 'id': 'aQs6q797mk0'},
		{'name': 'אני וגופי', 'type': 'youtube', 'id': 'm9Rc01MtBug'},
		{'name': 'לעשות דברים יחד', 'type': 'youtube', 'id': 'G9rdOcICH4s'},
		{'name': 'לטייל בארץ ישראל', 'type': 'youtube', 'id': 'SSAt1YsMlmI'},
		{'name': 'אני זה אני', 'type': 'youtube', 'id': 'fka2Ywelfy8'},
		{'name': 'יום הולדת', 'type': 'youtube', 'id': 'XTBDai-WIgk'},
		{'name': 'לחיות בשלום', 'type': 'youtube', 'id': '-CCjCf7Y728'},
		{'name': 'מי עושה מה', 'type': 'youtube', 'id': 'vmwBmFO3cqs'},
		{'name': 'כולם שונים', 'type': 'youtube', 'id': 'A10X30QEwes'},
	]},
	{"name":"דן ומוזלי", "type":"series", "shuffle":true, "episodes":[
		{'name': 'ביצי הפתעה', 'type': 'youtube', 'id': 'A2CV8udgAYA'},
		{'name': 'מקלחת', 'type': 'youtube', 'id': 'YGrp7QkmtOw'},
		{'name': 'קטן גדול', 'type': 'youtube', 'id': 'L1eDBvvA1HM'},
		{'name': 'מבצר הטעמים', 'type': 'youtube', 'id': '5HbvxFbmtJ8'},
		{'name': 'כריך טונה', 'type': 'youtube', 'id': 'YOkH1cvcqSE'},
		{'name': 'קוץ', 'type': 'youtube', 'id': '2vakJ5keL40'},
		{'name': 'קשה לקום בבוקר', 'type': 'youtube', 'id': 'oh7Ictxas-M'},
		{'name': 'גבינה מצחיקה', 'type': 'youtube', 'id': 'BDNOSvYSMjI'},
		{'name': 'לשחק עם האוכל', 'type': 'youtube', 'id': 'G48ths36Tcg'},
		{'name': 'הילולה', 'type': 'youtube', 'id': 'A36VWEDmli4'},
		{'name': 'אי ההשלמה', 'type': 'youtube', 'id': 'xY7kVDAkNlI'},
		{'name': 'אמנון וסוזט', 'type': 'youtube', 'id': 'Z8aX-gOYClw'},
		{'name': 'קטשופ', 'type': 'youtube', 'id': 'p8DJuZl99_o'},
		{'name': 'היום הכי קר', 'type': 'youtube', 'id': 'WotM-DbB9s0'},
		{'name': 'הציור הגדול', 'type': 'youtube', 'id': 'e7O-Zm2FZP8'},
		{'name': 'בלונים', 'type': 'youtube', 'id': 'BCGmxgEttgA'},
		{'name': 'מחבואים', 'type': 'youtube', 'id': 'qprZY7BAKEc'},
		{'name': 'נגיאף', 'type': 'youtube', 'id': 'a2pkY439Zk0'},
		{'name': 'גיחלצת', 'type': 'youtube', 'id': 'X7p5p2-zfgM'},
		{'name': 'הרצפה עקומה', 'type': 'youtube', 'id': 'O-LkLyVbvJc'},
		{'name': 'דן ומוזה', 'type': 'youtube', 'id': 'b3RJ5kBxy-g'},
		{'name': 'קורקינט צמרירי', 'type': 'youtube', 'id': 'jW6cwAqJhJQ'},
		{'name': 'באר המשאלות', 'type': 'youtube', 'id': 'k3tTXHOtb4s'},
		{'name': 'איכס פיכס', 'type': 'youtube', 'id': 'Qm3SpMYYP2Y'},
		{'name': 'די כבר', 'type': 'youtube', 'id': 'zIqwzdY_h7o'},
		{'name': 'הבטחות', 'type': 'youtube', 'id': '12PKPUP5VvM'},
		{'name': 'תחתונים', 'type': 'youtube', 'id': 'diy1lTa3x2g'},
		{'name': 'הרוח כועסת', 'type': 'youtube', 'id': 'XA5_xYTLjM0'},
		{'name': 'הדיוקנית של מוזלי', 'type': 'youtube', 'id': 'N0Vf_B21spA'},
		{'name': 'החלום של מוזלי - לקט', 'type': 'youtube', 'id': 'fZxlPDbOMZI'},
		{'name': 'בובה', 'type': 'youtube', 'id': 'exeQJSMFMWk'},
		{'name': 'להפסיק באמצע', 'type': 'youtube', 'id': 'HFoxe6NT-uI'},
		{'name': 'מזל', 'type': 'youtube', 'id': 'KkRNFbOoDCA'},
		{'name': 'קביים', 'type': 'youtube', 'id': 's7rssEa_UNU'},
		{'name': 'דבורים', 'type': 'youtube', 'id': 'Ey0RVawJmqc'},
		{'name': 'תרומה לחברה', 'type': 'youtube', 'id': 'G70sDcY0ka0'},
		{'name': 'היום הכי טוב', 'type': 'youtube', 'id': 'ABn6vzLRjaE'},
		{'name': 'הדיגדושית', 'type': 'youtube', 'id': 'nWPZ6GruT8A'},
		{'name': 'שכחת', 'type': 'youtube', 'id': 'cRVGhQLPPdM'},
		{'name': 'היום הכי קר שאפשר', 'type': 'youtube', 'id': 'kxdJ3stFnuA'},
		{'name': 'תבין לבד', 'type': 'youtube', 'id': 'PYNoKvdOph8'},
		{'name': 'החלום של קלופס', 'type': 'youtube', 'id': 'cTdTLejFP0g'},
		{'name': 'מד הכמה כמה', 'type': 'youtube', 'id': 'bWqlv_egnW0'},
		{'name': 'פיקניק', 'type': 'youtube', 'id': '-YPRztAe3DU'},
		{'name': 'מרק פטריות', 'type': 'youtube', 'id': 'hn04Ofm5P_k'},
		{'name': 'אכלו לי שתו לי', 'type': 'youtube', 'id': 'u3CUWsxeais'},
		{'name': 'מרמרת יום הולדת', 'type': 'youtube', 'id': 'Z6K7AwxgKco'},
		{'name': 'החדש', 'type': 'youtube', 'id': 'NvfeGFgtafA'},
		{'name': 'הפרחים לדן', 'type': 'youtube', 'id': 'Nwy7ZJCGlm0'},
		{'name': 'הצילו', 'type': 'youtube', 'id': '8Y1geTGIUNM'},
		{'name': 'שיקויים', 'type': 'youtube', 'id': 'CgOL0iqztUs'},
		{'name': 'די למשמוק', 'type': 'youtube', 'id': 'S2bJrqBbRDw'},
		{'name': 'פטפטת', 'type': 'youtube', 'id': 'ZSUZzCVqcrQ'},
		{'name': 'משקפיים', 'type': 'youtube', 'id': 'AMTtLi8G-hw'},
		{'name': 'לוף המנצח', 'type': 'youtube', 'id': 'DDrOHBYXPfU'},
		{'name': 'קרקס על הספה', 'type': 'youtube', 'id': '5JhmLGG0ZEU'},
		{'name': 'שני קלופס', 'type': 'youtube', 'id': '633EP8zsdKY'},
		{'name': 'יום או לילה', 'type': 'youtube', 'id': 'UJfmn3u3gdA'},
		{'name': 'נעל סירה', 'type': 'youtube', 'id': '-SASvyyoUrs'},
		{'name': 'לא רוצים לישון', 'type': 'youtube', 'id': 'xgANoHPtcxo'},
		{'name': 'אחים קטנים', 'type': 'youtube', 'id': '3Hz2W8Px5Yo'},
		{'name': 'החולה המדומה', 'type': 'youtube', 'id': 'eoDplKKs6sY'},
		{'name': 'כוכבים נופלים', 'type': 'youtube', 'id': '0Z1BQT9S--o'},
		{'name': 'שום כלום', 'type': 'youtube', 'id': 'c7tOpYJjPGw'},
		{'name': 'פפוזונים', 'type': 'youtube', 'id': 'oZJzRtM_FN4'},
		{'name': 'קלופס בכל הגדלים', 'type': 'youtube', 'id': 'jFak07Jv85U'},
		{'name': 'החבר שפוקי', 'type': 'youtube', 'id': 'cMAN15YoAL0'},
		{'name': 'לא להתערב', 'type': 'youtube', 'id': 'nbM2e47cr54'},
		{'name': 'עוד ועוד', 'type': 'youtube', 'id': 'Cu-MPHE5tXQ'},
		{'name': 'אפרוח', 'type': 'youtube', 'id': 'ZtxtOElg29M'},
		{'name': 'הר געש', 'type': 'youtube', 'id': 'CkXDxbU9tkQ'},
		{'name': 'יום או לילה', 'type': 'youtube', 'id': 'Sn6uhzTYdrk'},
		{'name': 'קולות לילה', 'type': 'youtube', 'id': 'zP7aWVhES5U'},
		{'name': 'געגועים', 'type': 'youtube', 'id': 'rHjwq9A__Rc'},
		{'name': 'גרנדה קונפיטורה', 'type': 'youtube', 'id': 'l1yLWiS3IYI'},
		{'name': 'זיכרון של טומבוחית', 'type': 'youtube', 'id': 'GLypHNZSGZk'},
		{'name': 'החלק הכי טוב', 'type': 'youtube', 'id': '-_5sop81H6o'},
		{'name': 'ספויילר', 'type': 'youtube', 'id': '20i3ptU530Q'},
		{'name': 'פרעצל אמר', 'type': 'youtube', 'id': 'SEisXGdbBzc'},
		{'name': 'שלט של האוטו', 'type': 'youtube', 'id': 'BD6hmuYed9c'},
		{'name': 'ההיפך מאמת', 'type': 'youtube', 'id': 'GeoGwElbbzg'},
		{'name': 'מפלצת', 'type': 'youtube', 'id': 'VpgAx1EteXs'},
		{'name': 'כדורגל וספל', 'type': 'youtube', 'id': 'uloVafjleaY'},
		{'name': 'אותו דבר כמו', 'type': 'youtube', 'id': 'f6Dq_hBynE4'},
		{'name': 'האמת', 'type': 'youtube', 'id': 'Pfys41ka4Lk'},
		{'name': 'הכינותי מראש', 'type': 'youtube', 'id': 'VOhpKP8WIrM'},
		{'name': 'להתבלבל', 'type': 'youtube', 'id': 'hLhwaFdJHaE'},
		{'name': 'התלהבות', 'type': 'youtube', 'id': '8_rV0mrqnbU'},
		{'name': 'הרחרחן', 'type': 'youtube', 'id': 'mHVhOswlVMk'},
		{'name': 'יער החושך', 'type': 'youtube', 'id': 'tnx-AT-ZKXM'},
		{'name': 'שביל הפירורים', 'type': 'youtube', 'id': 'jDh93wRMbAY'},
		{'name': 'מתנה למרמלדה - לקט', 'type': 'youtube', 'id': 'X3SsYrAFiEU'},
		{'name': 'חלילית', 'type': 'youtube', 'id': 'p3dwdCGxm68'},
		{'name': 'העיצבוקונים', 'type': 'youtube', 'id': 'cJ7hSLkh6l8'},
		{'name': 'התיקתק הירקרק', 'type': 'youtube', 'id': '2vogNBf9iWY'},
		{'name': 'תזמורת מלבי האש', 'type': 'youtube', 'id': 'aOi-HR0hf9o'},
		{'name': 'ברח קלופס, ברח', 'type': 'youtube', 'id': 'C1axKj6ONzM'},
		{'name': 'פופים', 'type': 'youtube', 'id': 'bXpIoQLxfkA'},
		{'name': 'בית המשפט', 'type': 'youtube', 'id': 'nYPT1Gptw14'},
		{'name': 'לא משעמם', 'type': 'youtube', 'id': 'kNJ9dmemsks'},
		{'name': 'אחר כך', 'type': 'youtube', 'id': 'Jbg7-dPxjXk'},
		{'name': 'אנחנו על המפה', 'type': 'youtube', 'id': 'iQCEcwHALKM'},
		{'name': 'קרקס על הספה', 'type': 'youtube', 'id': 'lYKZEXfaI0Y'},
		{'name': 'בשותף', 'type': 'youtube', 'id': '5pWToIZ9TiU'},
		{'name': 'יותר כיף', 'type': 'youtube', 'id': 'qtCngM8B9X0'},
	]},
	{"name":"קליפים", "type":"series", "shuffle":false, "episodes":[
		{'name': 'Grace Jones - I\'ve Seen That Face Before', 'type': 'dailyMotion', 'id': 'x16xse', 'newtab': false},
		{'name': 'Nina Hagen - Zarah', 'type': 'youtube', 'id': '5r5MBBRRn1Y'},
		{'name': 'The Triplets of Belleville - Belleville Rendez-vous', 'type': 'youtube', 'id': 'X-KChYBFiB0'},
		{'name': 'Elvis Presley - Jailhouse Rock', 'type': 'youtube', 'id': 'gj0Rz-uP4Mk', 'newtab': true},
		{'name': 'Queen - Bohemian Rhapsody', 'type': 'youtube', 'id': 'fJ9rUzIMcZQ', 'newtab': true},
		{'name': 'Nirvana - Smells Like Teen Spirit', 'type': 'dailyMotion', 'id': 'x3etcg'},
		{'name': 'Bohemian Rhapsody -  The Muppets', 'type': 'youtube', 'id': 'tgbNymZ7vqY'},
		{'name': 'System Of A Down - Chop Suey!', 'type': 'youtube', 'id': 'CSvFpBOe8eY'},
		{'name': 'OK Go - This Too Shall Pass', 'type': 'youtube', 'id': 'qybUFnY7Y8w'},
		{'name': 'OK Go - White Knuckles', 'type': 'youtube', 'id': '6lXVtCjJrz0'},
		{'name': 'Michael Jackson - Black Or White', 'type': 'youtube', 'id': '0RuAlyNclck'},
		{'name': 'The Supermen Lovers - Starlight', 'type': 'youtube', 'id': 'h61QG4s0I3U'},
		{'name': 'Gene Kelly - Singing In The Rain', 'type': 'youtube', 'id': 'D1ZYhVpdXbQ'},
		{'name': 'Good Morning (Singin\' in the Rain)', 'type': 'youtube', 'id': 'GB2yiIoEtXw'},
		{'name': 'Naughty by Nature - Hip Hop Hooray', 'type': 'youtube', 'id': 'Rz1Xn1vzOM4'},
		{'name': 'The Beatles - Yellow Submarine', 'type': 'youtube', 'id': 'm2uTFF_3MaA'},
		{'name': 'Somewhere over the Rainbow - Israel Kamakawiwoʻole', 'type': 'youtube', 'id': 'V1bFr2SWP1I'},
		{'name': 'Slayer - Seasons In The Abyss', 'type': 'youtube', 'id': 'I0yw1Qe_dww'},
		{'name': 'Madness - Our House', 'type': 'youtube', 'id': 'KwIe_sjKeAY'},
		{'name': 'Marrakech - Riff Cohen', 'type': 'youtube', 'id': '-o1Fk2G07MY'},
		{'name': 'ויקטוריה חנה - שיר ה-א\'-ב\'', 'type': 'youtube', 'id': 'Bl1epz3tSSA'},
		{'name': 'הבילויים - אוטו זבל', 'type': 'youtube', 'id': '8abdF3pI5lw'},
		{'name': 'ברי סחרוף - חלליות', 'type': 'youtube', 'id': 'm87iJUQme6w'},
		{'name': 'טיפקס - הורה נדלנים', 'type': 'youtube', 'id': 'VBnjY9mXNUQ'},
		{'name': 'פורטיס - לונדון תל אביב ברלין או בריסל', 'type': 'youtube', 'id': 'Ky7ZJJjN3Cc'},
		{'name': 'קרולינה - צר לי צ\'רלי', 'type': 'youtube', 'id': 'g7DLGA-e1q0'},
		{'name': 'פורטיס וברכה - משאית פיננסית', 'type': 'youtube', 'id': 'HYZMl8oaZi8'},
		{'name': 'פורטיס - סניאסי', 'type': 'youtube', 'id': 'OMIUt9VpQbs'},
		{'name': 'רמי פורטיס - תלוי על הצלב', 'type': 'youtube', 'id': '7A33TD-fxKk'},
		{'name': 'רמי פורטיס - את לא', 'type': 'youtube', 'id': 'fqScT2FUbRY'},
		{'name': 'רמי פורטיס - בלונדיניות על אוטוביאנקי', 'type': 'youtube', 'id': '50Hn801gGb8'},
		{'name': 'ברי סחרוף ורמי פורטיס - הדלת', 'type': 'youtube', 'id': 'VH9XKFF_lfI'},
		{'name': 'פורטיס - חתול מפלצת', 'type': 'youtube', 'id': 'VxwkddbyZM8'},
		{'name': 'רמי פורטיס - שועל במנוסה', 'type': 'youtube', 'id': 'kYU151VE9yQ'},
		{'name': 'רד בנד ורמי פורטיס - רד מעל מסך הטלוויזיה שלי', 'type': 'youtube', 'id': 'fnjRgCYvwRs'},
		{'name': 'רמי פורטיס - חשיפה מוגזמת מסוכנת לעור', 'type': 'youtube', 'id': '-7mKiMAKnXc'},
		{'name': 'רמי פורטיס - אין קשר', 'type': 'youtube', 'id': 'wmbH2Kyr40w'},
		{'name': 'רמי פורטיס ורד בנד- Reflections of my Life', 'type': 'youtube', 'id': 'aOe2dkdJtuc'},
		{'name': 'פורטיס - מדור פיות', 'type': 'youtube', 'id': 'MOM42Q3o4j8'},
		{'name': 'פורטיס - לקשקש בזנב', 'type': 'youtube', 'id': '3u_mF_TgKtw'},
		{'name': 'פורטיסחרוף - אגם ענקית', 'type': 'youtube', 'id': 'FfkFXusrFrE'},
		{'name': 'פורטיס - בלי ראש אין ראש', 'type': 'youtube', 'id': 'gXrVRpr-0n0'},
		{'name': 'פורטיס - רד מעל מסך הטלוויזיה שלי', 'type': 'youtube', 'id': 'PvcyJcSlKsk'},
		{'name': 'הקליק - אינקובטור', 'type': 'youtube', 'id': '-p1Bty-fu8o'},
		{'name': 'The GAG Quartet - le Internet Medley', 'type': 'youtube', 'id': 'mghhLqu31cQ'},
		{'name': 'The Phantom Of The Opera', 'type': 'youtube', 'id': '-JaeBxYCI9k'},
		{'name': 'Dschinghis Khan - Dschinghis Khan', 'type': 'youtube', 'id': 'pzmI3vAIhbE'},
		{'name': 'אריק איינשטיין - שבת בבוקר', 'type': 'youtube', 'id': 'fwE-jj_GQvw'},
		{'name': 'אריק איינשטיין - שבת בבוקר', 'type': 'youtube', 'id': 'MGAjlqg5URg'},
		{'name': 'אריק איינשטיין - אדון שוקו', 'type': 'youtube', 'id': '4Ij1CaPrQio'},	
		{'name': 'איתן אולמן - כמעט טוב', 'type': 'youtube', 'id': 'lc2D4LVzxBc'},
		{'name': 'אריק איינשטיין - מכופף הבננות', 'type': 'youtube', 'id': 'UrnxJrmHRWY'},
		{'name': 'דני סנדרסון - אצל הדודה והדוד', 'type': 'youtube', 'id': 'Vw7KCMjvs6I'},
		{'name': 'מתי כספי - סטירת לחי', 'type': 'youtube', 'id': 'Swi-xC1EoEM'},
		{'name': 'מתי כספי - נחליאלי', 'type': 'youtube', 'id': '8umyOmFEQ6M'},
		{'name': 'מתי כספי - מוריס והיונים', 'type': 'youtube', 'id': 'solO8qMK4fw'},
		{'name': 'שלמה גרוניך - קואיננה', 'type': 'youtube', 'id': 'Z72zzL-lmmU'},
		{'name': 'Brett Domino: Justin Timberlake Medley', 'type': 'youtube', 'id': 'xTwweLJ78KE'},
	]},
	{"name":"סמי הכבאי", "type":"series", "shuffle":true, "episodes":[
		{'name': 'תפוס את החרק', 'type': 'youtube', 'id': 'TmVu0eSt-xU'},
		{'name': 'החניכים הצעירים יוצאים לשטח', 'type': 'youtube', 'id': 'nXgA9BQCjC8'},
		{'name': 'סוס במנוסה', 'type': 'youtube', 'id': 'vWP22VxasCI'},
		{'name': 'גיבורי הסופה (שעה)', 'type': 'youtube', 'id': 'yw1gocZyn8o'},
		{'name': 'כדורגל בוער', 'type': 'youtube', 'id': 'iivFbCP_JUE'},
		{'name': 'אבעבועות רוח', 'type': 'youtube', 'id': 'u8cJy9OU8ms'},
		{'name': 'טיפים למדורה', 'type': 'youtube', 'id': 'tGlH9DWaY9U'},
		{'name': 'מופע הצפרדע', 'type': 'youtube', 'id': 'xyMO29wmCbU'},
		{'name': 'פחד במה', 'type': 'youtube', 'id': 'T1-S3TPw8MI'},
		{'name': 'השריפה הגדולה של פונטי פנדי (שעה)', 'type': 'youtube', 'id': 'e3ChxP5afl4'},
		{'name': 'אדלה דוהרת', 'type': 'youtube', 'id': 'IGQ0mc6tYMU'},
		{'name': 'הגיבור החדש', 'type': 'youtube', 'id': 'jz-ZCnPYlY0'},
		{'name': 'הקרקס של אדם', 'type': 'youtube', 'id': 'lxE-R_GrpVo'},
		{'name': 'יום האם', 'type': 'youtube', 'id': 'bov9Sl1t-_c'},
		{'name': 'מחבואים', 'type': 'youtube', 'id': 'cQCc8ZtdIs0'},
		{'name': 'מים עמוקים', 'type': 'youtube', 'id': 'fmsDwtnj8gM'},
		{'name': 'פונטי פנדי בפארק', 'type': 'youtube', 'id': 'OcqwAN8RC74'},
		{'name': 'הלילה המפחיד של אדם', 'type': 'youtube', 'id': 'JOOIMxPJ7PQ'},
		{'name': 'אל על', 'type': 'youtube', 'id': 'kvi221gtIdI'},
		{'name': 'שיט בסירה', 'type': 'youtube', 'id': 'i2xKuUGeLhA'},
		{'name': 'יומו של הפינגווין', 'type': 'youtube', 'id': 's1AjvJqHHJI'},
		{'name': 'תקועים בבוץ', 'type': 'youtube', 'id': 'xvBHUVeCWKY'},
		{'name': 'מהומת הפיצה', 'type': 'youtube', 'id': 'RVyP11Uw_NE'},
		{'name': 'בורחים מפונטי פנדי', 'type': 'youtube', 'id': 'V66MzvZvh3o'},
		{'name': 'כלב ההצלה', 'type': 'youtube', 'id': 'HpP80PyGVIc'},
		{'name': 'קר כבשים', 'type': 'youtube', 'id': 'VHLrqpA3eTo'},
		{'name': 'מטמון ממולכד', 'type': 'youtube', 'id': '53HQT7ECfR8'},
		{'name': 'שיעור נהיגה', 'type': 'youtube', 'id': '-RFy7thyRIY'},
		{'name': 'אהבה בוערת', 'type': 'youtube', 'id': '5-2GzwAZCl0'},
		{'name': 'מזיק מחמד', 'type': 'youtube', 'id': '_DJob5GN0eY'},
		{'name': 'שביל מסוכן', 'type': 'youtube', 'id': 'KNkihR55T1w'},
		{'name': 'משטח ההוקי נמס', 'type': 'youtube', 'id': 'HyTTEfjp6Vk'},
		{'name': 'האוצר של פונטי פנדי', 'type': 'youtube', 'id': 'MiaHwZBXKPY'},
		{'name': 'הדינוזאור מהאגם', 'type': 'youtube', 'id': 'qrHBTRlTpgE'},
		{'name': 'פנסי הנייר', 'type': 'youtube', 'id': 'hVRB4y079ws'},
		{'name': 'דב נצרים', 'type': 'youtube', 'id': 'tEZDCgKxd0Y'},
		{'name': 'מה, מה, תינוק קטן', 'type': 'youtube', 'id': '2k9QLfL8uV0'},
		{'name': 'דרך ללא מוצא', 'type': 'youtube', 'id': 'zVRIvSaj_qA'},
		{'name': 'יום הולדת לסמי', 'type': 'youtube', 'id': 'jFZkHa-G5TU'},
		{'name': 'רכבת לילה', 'type': 'youtube', 'id': 'rshDAqx1KfM'},
		{'name': 'ציד צבים', 'type': 'youtube', 'id': '0UkTBR1ax6s'},
		{'name': 'גל חום', 'type': 'youtube', 'id': 'faJ60XarCzE'},
		{'name': 'הרפתקת המאובנים הגדולה של אדם', 'type': 'youtube', 'id': 'BSzhzn5y53M'},
		{'name': 'הכלבה', 'type': 'youtube', 'id': 'mqm73MFSxoQ'},
		{'name': 'העגלה צפה', 'type': 'youtube', 'id': '32i-hP5o5pQ'},
		{'name': 'מפולת', 'type': 'youtube', 'id': 'kURCY7pknEQ'},
		{'name': 'מסיבת הפיג\'מות הכי טובה בעולם', 'type': 'youtube', 'id': '8yrkq9BrOXo'},
		{'name': 'ארמונות ומלכים', 'type': 'youtube', 'id': '24SpdjGaGy4'},
		{'name': 'חילוץ בין הסלעים', 'type': 'youtube', 'id': 'oFxz2_5HXlw'},
		{'name': 'חתור', 'type': 'youtube', 'id': 'AJydZBW-Km4'},
		{'name': 'אבודים במערות', 'type': 'youtube', 'id': 'Y6N_IOhgDN4'},
		{'name': 'כושר הוא אושר', 'type': 'youtube', 'id': 'TNuy4AzEFCk'},
		{'name': 'דרך ללא מוצא', 'type': 'youtube', 'id': 'zVRIvSaj_qA'},
		{'name': 'מסיבת האימה', 'type': 'youtube', 'id': '9g_Q4f_ntO8'},
		{'name': 'יום הולדת לסמי', 'type': 'youtube', 'id': 'jFZkHa-G5TU'},
		{'name': 'מצב דביק', 'type': 'youtube', 'id': 'bs_P239j5RI'},
		{'name': 'צרות באוטובוס', 'type': 'youtube', 'id': 'dSAKP7uNnp4'},
		{'name': 'צ\'ארלי והדיג המוצלח', 'type': 'youtube', 'id': 'OhvUBLOCjxw'},
		{'name': 'ארמונות ומלכים', 'type': 'youtube', 'id': '24SpdjGaGy4'},
		{'name': 'צרה צרורה', 'type': 'youtube', 'id': 'yjzGOETNJdM'},
		{'name': 'צרות צרורות', 'type': 'youtube', 'id': 'JJDwoNi-194'},
		{'name': 'לקוח המיליון', 'type': 'youtube', 'id': 'M8mjD_RM7Sw'},
	]},
	{"name":"סרטונים", "type":"series", "shuffle":true, "episodes":[
		{'name': 'שלושת החזירונים', 'type': 'youtube', 'id': '3X9cD4QKaZU'},
		{'name': 'מיקי מאוס - שעת סימפוניה', 'type': 'youtube', 'id': '1X8tP4W4ZfM'},
		{'name': 'דונלד דאק - הברז הדולף', 'type': 'youtube', 'id': '19IbrAmAxS0'},
		{'name': 'דונלד דאק - השכן החדש', 'type': 'youtube', 'id': 'fwFvr4NM9sU'},
		{'name': 'אדם', 'type': 'youtube', 'id': 'd6-ek6g04b8'},
		{'name': 'הטבח השוודי מכין פופקורן', 'type': 'youtube', 'id': 'B7UmUX68KtE'},
		{'name': 'אורמי החזיר', 'type': 'youtube', 'id': 'EUm-vAOmV1o'},
		{'name': 'פטר והזאב', 'type': 'youtube', 'id': 'c90HmNb75bA', 'newtab': true},
		{'name': 'שמוליק קיפוד, הצב של אורן, הלו הלו אבא', 'type': 'youtube', 'id': 'qSOsMgZ1iwk'},
		{'name': 'סיפורי התנך לילדים', 'type': 'youtube', 'id': 'OZKwT5LPR0k'},
		{'name': 'יציאת מצרים', 'type': 'youtube', 'id': '17AbVJkQRck'},
		{'name': 'מעשה באפרוח שהלך לחפש אמא אחרת', 'type': 'youtube', 'id': 'hZsfA767ctU'},
		{'name': 'רצף תשדירי ירקות', 'type': 'youtube', 'id': '1_2W6BbKIRs'},
		{'name': 'ספגטי', 'type': 'youtube', 'id': 'qBjLW5_dGAM'},
		{'name': 'סלט אבוקדו', 'type': 'youtube', 'id': 'dNJdJIwCF_Y'},
		{'name': 'יאן שוואנקמאייר - אוכל', 'type': 'youtube', 'id': 'rPPw1c7lrA0'},
		{'name': 'שביל ישראל בלי לדרוך על הקרקע', 'type': 'youtube', 'id': 'TidJdOmsj98'},
	]},
	{"name":"טוב טוב הגמד", "type":"series", "shuffle":false, "episodes":[
		{'name': 'פרק 1', 'type': 'youtube', 'id': 'dDYwyLm4js8'},
		{'name': 'פרק 3', 'type': 'dailyMotion', 'id': 'x170v58'},
		{'name': 'פרק 4', 'type': 'youtube', 'id': '1fMQhzmLc7o'},
		{'name': 'פרק 6', 'type': 'youtube', 'id': 'QbrND5x_mAc', newtab: true},
		//{'name': 'פרק 8', 'video': 'טוב טוב הגמד\'},
		{'name': 'פרק 11', 'type': 'youtube', 'id': 'eVWu_g8s_V8'},
		{'name': 'פרק 12', 'type': 'youtube', 'id': 'VcPxC8DwVkk'},
		{'name': 'פרק 13', 'type': 'youtube', 'id': '0_Up9CImDxg'},
		{'name': 'פרק 14', 'type': 'youtube', 'id': 'cS983aPnyaw'},
		{'name': 'פרק 15', 'type': 'youtube', 'id': '-M-1jJtuPoY'},
		{'name': 'פרק 16', 'type': 'youtube', 'id': 'p1qiry-VyR8'},
		{'name': 'פרק 17', 'type': 'youtube', 'id': 'fKFzjVO8ELQ'},
		{'name': 'פרק 18', 'type': 'youtube', 'id': 'Uex_2F5dbZc'},
		{'name': 'פרק 19', 'type': 'youtube', 'id': 'mcTTyMwftTs'},
		{'name': 'פרק 20', 'type': 'youtube', 'id': 'eV6nBz5eZ8s'},
		{'name': 'פרק 21', 'type': 'youtube', 'id': 'qWnCfzG4d2U'},
		{'name': 'פרק 22', 'type': 'youtube', 'id': '1oL-s999lc0'},
		{'name': 'פרק 23', 'type': 'youtube', 'id': 'LLZZoC9lBQA'},
		{'name': 'פרק 24', 'type': 'youtube', 'id': 'fKNENx6Y36o'},
		{'name': 'פרק 25', 'type': 'youtube', 'id': 'UiOebYDjWho'},
		{'name': 'פרק 26', 'type': 'youtube', 'id': 'xy-vlDYVx2Y'},
	]},
	{"name":"קלטות ילדים ומופעים", "type":"series", "shuffle":true, "episodes":[
		{'name': 'פיטר פן - המחזמר 1988', 'type': 'youtube', 'id': '9Q3f9xk291o'},
		{'name': 'אפרוחים', 'type': 'youtube', 'id': 'b7vcn1pHqEg'},
		{'name': 'מפתחות הקסם של דידי', 'type': 'youtube', 'id': 'Y-_sh8fEYzY'},
		{'name': 'פים פם פה', 'type': 'youtube', 'id': 'ZjJdp6jrBhM'},
		{'name': 'פסטיגל 1987 - חלק א', 'type': 'youtube', 'id': 'MI1Mm2G2zYA'},
		{'name': 'מה פתאום - משירי ע. הלל', 'type': 'youtube', 'id': 'XUTPQbNQt3Y'},
		{'name': 'אריק איינשטיין - כמו גדולים', 'type': 'youtube', 'id': 'OhYY4qCLtA0'},
		{'name': 'אריק איינשטיין - כמו גדולים 2', 'type': 'youtube', 'id': 'jZq3R7ceFJw'},
		{'name': 'שירים קטנים 2', 'type': 'youtube', 'id': '81UYl1dpl1o'},
		{'name': 'עוץ לי גוץ לי - המחזמר', 'type': 'youtube', 'id': 'E-o3MMFxrZA'},
		{'name': 'טוויגי - גיבור בריאות', 'type': 'youtube', 'id': 'R3B5GtoxIW4'},
	]},
	{"name":"החיים", "type":"series", "shuffle":false, "episodes":[
		{'name': '1 - התא', 'type': 'youtube', 'id': 'OoXE0pypuuQ'},
		{'name': '2 - הלידה', 'type': 'youtube', 'id': 'z8IHw58fZ40'},
		{'name': '3 - הזקיפים השומרים על הגוף', 'type': 'youtube', 'id': 'c-_sDs0wiZs'},
		{'name': '4 - מח העצמות', 'type': 'youtube', 'id': '6nuicHjL4ic'},
		{'name': '5 - כלי הדם', 'type': 'youtube', 'id': 'hpHF_VeNGmI'},
		{'name': '6 - לוחית הדם', 'type': 'youtube', 'id': 'C2ZjjaTAL18'},
		{'name': '7 - הלב', 'type': 'youtube', 'id': 'TLdKY6JxCHI'},
		{'name': '8 - הנשימה', 'type': 'youtube', 'id': 'LrnYAMVUVjA'},
		{'name': '9 - המח', 'type': 'youtube', 'id': 'Fz6dEIEYNLw'},
		{'name': '10 - הנוירונים', 'type': 'youtube', 'id': 'ds3Ic4W-BgI'},
		{'name': '11 - העין', 'type': 'youtube', 'id': '7g67QCitGic'},
		{'name': '12 - האוזן', 'type': 'youtube', 'id': 'nrauzttA5tI'},
		{'name': '13 - העור', 'type': 'youtube', 'id': 'qnqvCwifctQ'},
		{'name': '14 - הפה והשיניים', 'type': 'youtube', 'id': '1wgr67waRXE'},
		{'name': '15 - מערכת העיכול', 'type': 'youtube', 'id': 'iVjL_DUk5p8'},
		{'name': '16 - הכבד', 'type': 'youtube', 'id': 'jQo7k7PTUG8'},
		{'name': '17 - הכליות', 'type': 'youtube', 'id': 'TVcXCfxx4Ok'},
		{'name': '18 - המערכת הלימפטית', 'type': 'youtube', 'id': 'XERxQOLH2Pg'},
		{'name': '19 - העצמות והשלד', 'type': 'youtube', 'id': 'TTAVol7d-3A'},
		{'name': 'השרירים והשומן', 'type': 'youtube', 'id': 'OqI16GfrcoY'},
		{'name': 'המלחמה ברעלנים', 'type': 'youtube', 'id': 'l2U2IOlqq_4'},
		{'name': '22 - החיסון', 'type': 'youtube', 'id': 'R5DupUCybB8'},
		{'name': '23 - ההורמונים', 'type': 'youtube', 'id': 'yKSKpouY7yU'},
		{'name': '24 - שרשראות החיים', 'type': 'youtube', 'id': 'wnXHupddGq0'},
		{'name': '25 - תיקונים ושינויים', 'type': 'youtube', 'id': 'G9yIl667JPI'},
		{'name': '26 - החיים נמשכים', 'type': 'youtube', 'id': 'AVrD06iGq0Y'},
	]},
	{"name":"המומינים", "type":"series", "shuffle":false, "episodes":[
		{'name': 'כוכב השביט (סרט מקדים)', 'type': 'youtube', 'id': '7r5YsKqwlTg'},
		{'name': '1 - אביב בעמק המומינים', 'type': 'dailyMotion', 'id': 'x5giymz'},
		{'name': '2 - המגבעת', 'type': 'dailyMotion', 'id': 'x5jcjt5'},
		{'name': '3 - הסירה הנטושה', 'type': 'dailyMotion', 'id': 'x5jgf5z'},
		{'name': '4 - אי השמנטפים', 'type': 'dailyMotion', 'id': 'x5jggg1'},
		{'name': '5 - כל מיני מציאות', 'type': 'dailyMotion', 'id': 'x5jgi65'},
		{'name': '6 - אורחים קטנים', 'type': 'dailyMotion', 'id': 'x5jgio4'},
		{'name': '7 - המזוודה', 'type': 'dailyMotion', 'id': 'x6dn36g'},
		{'name': '8 - המכשף', 'type': 'dailyMotion', 'id': 'x5jzjix'},
		{'name': '9 - חברה בלתי נראית', 'type': 'dailyMotion', 'id': 'x5jzjiy'},
		{'name': '10 - ניני צוחקת', 'type': 'dailyMotion', 'id': 'x5jzjj0'},
		{'name': '11 - סנורק ממריא', 'type': 'dailyMotion', 'id': 'x5k3cf7'},
		{'name': '12 - בת ערובה', 'type': 'dailyMotion', 'id': 'x5k3gvt'},
		{'name': '13 - הדרקון האחרון', 'type': 'dailyMotion', 'id': 'x5kcmln'},
		{'name': '14 - שכנים חדשים', 'type': 'dailyMotion', 'id': 'x5kcmlo'},
		{'name': '15 - נסיכה ליום אחד', 'type': 'dailyMotion', 'id': 'x5kcmlp'},
		{'name': '16 - יצורים מהחלל', 'type': 'dailyMotion', 'id': 'x5kcmlq'},
		{'name': '17 - מומינאבא משתוקק להרפתקה', 'type': 'dailyMotion', 'id': 'x5kcmlr'},
		{'name': '18 - זרעי קסם', 'type': 'dailyMotion', 'id': 'x5kljmb'},
		{'name': '19 - סכנות בג\'ונגל', 'type': 'dailyMotion', 'id': 'x5kljmd'},
		{'name': '20 - בחזרה לגן החיות', 'type': 'dailyMotion', 'id': 'x5kljme'},
		{'name': '21 - סנופקין יוצא לדרך', 'type': 'dailyMotion', 'id': 'x5kzbmz'},
		{'name': '22 - הגבירה קרה', 'type': 'dailyMotion', 'id': 'x5kx7bn'},
		{'name': '23 - אורחים בחורף', 'type': 'dailyMotion', 'id': 'x5kx7bo'},
		{'name': '24 - געגועים לסנופקין', 'type': 'dailyMotion', 'id': 'x5l9cv5'},
		{'name': '25 - המגדלור', 'type': 'dailyMotion', 'id': 'x5l983n'},
		{'name': '26 - שומר המגדלור', 'type': 'dailyMotion', 'id': 'x5lzmsk'},
		{'name': '27 - הדודה העשירה', 'type': 'dailyMotion', 'id': 'x5lc8gk'},
		{'name': '28 - התיאטרון הצף', 'type': 'dailyMotion', 'id': 'x5lzn1j'},
		{'name': '29 - חג אמצע הקיץ', 'type': 'dailyMotion', 'id': 'x5lzn1n'},
		{'name': '30 - הילדים האבודים', 'type': 'dailyMotion', 'id': 'x5lzn1o'},
		{'name': '31 - מר נוח', 'type': 'dailyMotion', 'id': 'x5mesjo'},
		{'name': '32 - דג הזהב', 'type': 'dailyMotion', 'id': 'x5met5e'},
		{'name': '33 - מנורת הקסמים', 'type': 'dailyMotion', 'id': 'x5p2wq8'},
		{'name': '34 - העפיפון', 'type': 'dailyMotion', 'id': 'x5p0l19'},
		{'name': '35 - המכשפה', 'type': 'dailyMotion', 'id': 'x5p303d'},
		{'name': '36 - הולכים לישון', 'type': 'dailyMotion', 'id': 'x5p0l1a'},
		{'name': '37 - המדורה הגדולה', 'type': 'dailyMotion', 'id': 'x5p0kzy'},
		{'name': '38 - תרדמת כשפים', 'type': 'dailyMotion', 'id': 'x5p304p'},
		{'name': '39 - קולות פיצוץ בלילה', 'type': 'dailyMotion', 'id': 'x5p304q'},
		{'name': '40 - סוד הזיקוקים', 'type': 'dailyMotion', 'id': 'x5qtg8a'},
		{'name': '41 - הגנב הבלתי נראה', 'type': 'dailyMotion', 'id': 'x5qtgbd'},
		{'name': '42 - ליקוי חמה', 'type': 'dailyMotion', 'id': 'x5qtgvf'},
		{'name': '43 - הכוכבת', 'type': 'dailyMotion', 'id': 'x5r3zvi'},
		{'name': '44 - המתנה', 'type': 'dailyMotion', 'id': 'x5qth3k'},
		{'name': '45 - מומין בונה בית', 'type': 'dailyMotion', 'id': 'x5ru337'},
		{'name': '46 - אחוזת צ\'אנדוס', 'type': 'dailyMotion', 'id': 'x5ru52p'},
		{'name': '47 - המעיין החם', 'type': 'dailyMotion', 'id': 'x5ru7dq'},
		{'name': '48 - בועות', 'type': 'dailyMotion', 'id': 'x5rucyo'},
		{'name': '49 - דלעת הענק', 'type': 'dailyMotion', 'id': 'x5ruizh'},
		{'name': '50 - השד הנורא', 'type': 'dailyMotion', 'id': 'x5saerw'},
		{'name': '51 - מגדת העתידות', 'type': 'dailyMotion', 'id': 'x5sagp6?playlist=x4vu6k'},
		{'name': '52 - מחפשים את המטמון', 'type': 'dailyMotion', 'id': 'x5sahql?playlist=x4vu6k'},
		{'name': '53 - נימפת הים', 'type': 'dailyMotion', 'id': 'x5sal8a?playlist=x4vu6k'},
		{'name': '54 - היהלום של בימבל', 'type': 'dailyMotion', 'id': 'x5saoem?playlist=x4vu6k'},
		{'name': '55 - מומינאבא רוצה להיות צעיר', 'type': 'dailyMotion', 'id': 'x5sb0lr?playlist=x4vu6k'},
		{'name': '56 - העמק הנסתר', 'type': 'dailyMotion', 'id': 'x5tkkk9?playlist=x4vu6k'},
		{'name': '57 - אהבת אם', 'type': 'dailyMotion', 'id': 'x5tjq8c?playlist=x4vu6k'},
		{'name': '58 - אמנים בעמק', 'type': 'dailyMotion', 'id': 'x5tkmg3?playlist=x4vu6k'},
		{'name': '59 - מסיפורי מומינאבא', 'type': 'dailyMotion', 'id': 'x5tmdxn?playlist=x4vu6k'},
		{'name': '60 - מאי ותעלוליה', 'type': 'dailyMotion', 'id': 'x5tmp8q?playlist=x4vu6k'},
		{'name': '61 - מומין חוזה עתידות', 'type': 'dailyMotion', 'id': 'x5tnw2j?playlist=x4vu6k'},
		{'name': '62 - ללכת ולעוף', 'type': 'dailyMotion', 'id': 'x5to2pa?playlist=x4vu6k'},
		{'name': '63 - הרפתקאות מומינאבא', 'type': 'dailyMotion', 'id': 'x5tpeq2?playlist=x4vu6k'},
		{'name': '64 - מומין והציפורים', 'type': 'dailyMotion', 'id': 'x5tpjvu?playlist=x4vu6k'},
		{'name': '65 - הנשף', 'type': 'dailyMotion', 'id': 'x5vck9z?playlist=x4vu6k'},
		{'name': '66 - הערפד', 'type': 'dailyMotion', 'id': 'x5tsc9z?playlist=x4vu6k'},
		{'name': '67 - הכיסא', 'type': 'dailyMotion', 'id': 'x5vck9w?playlist=x4vu6k'},
		{'name': '68 - הספינה', 'type': 'dailyMotion', 'id': 'x5vck9x?playlist=x4vu6k'},
		{'name': '69 - עוף החול', 'type': 'dailyMotion', 'id': 'x5vf7j3?playlist=x4vu6k'},
		{'name': '70 - דבק הפלא', 'type': 'dailyMotion', 'id': 'x5wo0fq?playlist=x4vu6k'},
		{'name': '71 - הפטרייה המוזרה', 'type': 'dailyMotion', 'id': 'x5wo0fr?playlist=x4vu6k'},
		{'name': '72 - מעמקי הים', 'type': 'dailyMotion', 'id': 'x5wo0fs?playlist=x4vu6k'},
		{'name': '73 - האי העגול', 'type': 'dailyMotion', 'id': 'x5wo0ft?playlist=x4vu6k'},
		{'name': '74 - הצמח המזמר', 'type': 'dailyMotion', 'id': 'x5woz4z?playlist=x4vu6k'},
		{'name': '75 - אזמרגד המלכה', 'type': 'dailyMotion', 'id': 'x5ws8zt?playlist=x4vu6k'},
		{'name': '76 - הבית של המיולין', 'type': 'dailyMotion', 'id': 'x5wvir8?playlist=x4vu6k'},
		{'name': '77 - התחרות', 'type': 'dailyMotion', 'id': 'x5wwv0g?playlist=x4vu6k'},
		{'name': '78 - סוף הסתיו', 'type': 'dailyMotion', 'id': 'x5wvira?playlist=x4vu6k'},
		{'name': '79א', 'type': 'youtube', 'id': 'lZPSB2ft1N8'},
		{'name': '79ב', 'type': 'youtube', 'id': '5wSShaJqHbQ'},
		{'name': '100 - ירח אדום', 'type': 'youtube', 'id': '0mA2Wz64E_4'},
		{'name': '102 - יום הולדת', 'type': 'youtube', 'id': 'ZjXRIj-EXZM'},
	]},
	{'name': 'עולם הבובות של גלי: השועל והחסידה', 'type': 'youtube', 'id': 'YwGM4ixkfNo'},
];
